---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onechart
  namespace: romm
spec:
  interval: 12h
  url: https://chart.onechart.dev
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: romm
spec:
  type: "oci"
  interval: 10m0s
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: romm
  namespace: romm
spec:
  image: rommapp/romm
  interval: 12h