apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: connector
  namespace: tailscale
  annotations:
    # Retain recovery egress if its parent source is accidentally pruned.
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  exitNode: true
