apiVersion: v1
kind: Service
metadata:
  name: homeassistant-egress
  namespace: kube-system
  annotations:
    tailscale.com/proxy-group: tsidp-egress
    tailscale.com/tailnet-fqdn: homeassistant.${ts_net}
spec:
  type: ExternalName
  externalName: placeholder.invalid
  ports:
    - name: https
      port: 443
      protocol: TCP
