---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mcp-credentials
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_SERVICE_ACCOUNT_TOKEN: AgCs5CPsRTGLN1CdUNIrM1zj5+tVKgsUhEcwFeGKkZic56NrwF7npx1c1tsJ+oejRLyxiJ8F9J3u0efk+WvkJHcelXqyvMbB08hC4vGlb+ufv53bIXTgWDQ2ntpCkwtwmp9yfEQiN1sYvvzE/+jccwszXpCjXiZyH3uSW7wICAAbmbeyWUu85zeFP/arbca9LMcukEDAQhEclH8bzG+LkXXFqoGDdABahFDk7RfbjSNRa+CiRTb8VFcv4Se+CoccLpmSzPQdyumzqvat4tJc71MEhJeNq7nVT6kuBow+Px76a2z/FPZf/QE+SEIR3fMGOXAUmhDkd5D94dGm9e3Zyqeh7r2E3t5QEI9M5JZTXydKqjvDAzHBs/f4tM95rhlixrb+2zIkWRTr49/j0A1VDwRTEnDnp4AiFvb+2XXwgDP0i/UJSS5Cj+vmlLg1ZaSGEFZaLzuMosDoU08CAfucTs9nCTCp54ZqXQ5MiAoJ4Jmdjw+9/Vpuc317PDjZwVM2blWy14HCpNXhWdgkSX0zxsoq9tLxAwLLfzLmQxZPA864hoEyGIcpRfb34cnPmqEMqn5n6mwncugIV5xHuoqrFXH0gyNS58/qPpmxNgk8GyVb9PDSftllJ2ZR0+t4AGOz8/nweScUPKDhZFxSssElBLFTrVaC96SOmpiPff277nXK59XuKWw9AhJmBgztkII2LY7nU1qmIyJb3ozYeXDIF2CPISlwGJVZ63w+Ob6QbHf/m5P/nryuKz8u9BiL8Ub6
  template:
    metadata:
      name: grafana-mcp-credentials
      namespace: monitoring
