---
# This is a placeholder SealedSecret for Grafana MCP credentials.
# To create the actual sealed secret with your Grafana service account token, run:
#
# kubectl create secret generic grafana-mcp-credentials \
#   --namespace=monitoring \
#   --from-literal=GRAFANA_URL='http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80' \
#   --from-literal=GRAFANA_SERVICE_ACCOUNT_TOKEN='<your-token-from-grafana>' \
#   --dry-run=client -o yaml | \
#   kubeseal --cert etc/certs/pub-sealed-secrets.pem \
#   --format=yaml > monitoring/controllers/grafana-mcp/grafana-mcp-credentials-sealed-secret.yaml
#
# Prerequisites:
# 1. Create service account in Grafana UI: Administration → Service Accounts
# 2. Name: grafana-mcp-server
# 3. Role: Editor
# 4. Generate token and use it in the command above
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mcp-credentials
  namespace: monitoring
spec:
  encryptedData:
    # Replace these placeholder values by running the kubeseal command above
    # GRAFANA_URL: <encrypted-value>
    # GRAFANA_SERVICE_ACCOUNT_TOKEN: <encrypted-value>
    placeholder: "placeholder"  # Temporary value until sealed secret is generated
  template:
    metadata:
      name: grafana-mcp-credentials
      namespace: monitoring
    type: Opaque
