---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mcp-credentials
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_SERVICE_ACCOUNT_TOKEN: AgAOFBpBXpkYDnZaAPRjA+BVB4J+P55YZHClugamyvJSyBOoFD0DJG+IiN78UegXq4ssFK5CspfNxdN17OopTGRidmuCGlJIg5XRbB1j+9cLQkTNDUNVKdaH+i0/uR4uqluCDbKAhPWEl2iZLvp1VTP1H1I82gw6octIP/u7d49tHLRqs/ag7JFAZP4PagZp9XQP05DO3hW3grzHwDtUPQwT/7vI6Z4qd+nrUHRRCBtWLpe4jl0O3GKl+I8qKJsOfB8BzcPIazF/Bk18nJYhgcpNf8VQeoxx3hVCkhIUd2FNo4Snpee3LvRWcDy3vUMFP1hdlIRzAVOKw7h+bSBAhW7/pluRAoD9Up6uEpUyOd3AscEpQeWkAlW1SzjZIf7uqYLb+IswzA/KGlFJZ45kQUuaki3/bhIRfVAJGTI3OQfGAhRWpW0dhQnLP4fVbccnkhBpR5M7hGuhHd3b5vm82unsU2nyMSqcTo0xAiF8RqL7+941YhEh/NeKwVEau3ujXJX9ObiCYf0S+RWHMd3ujpeDVKfAWvtMm5Oilm4MmtofMEATHVKPUdK5Vg1F1YiDRdfA0baUsOUh83QyzRwLb5uOYpiuXcJ4fZcKZt6BVcd9sdZJlv2cwrtYMhM1/GPlJJYgxHopTfK4Sqx/xxur76o6bQtM532zO0goT27Fd27b8Mkw90+6swx6OmtbmWY55GocPSsdtjkLCZ4s4kvNOzcMdN3JIaf4xDGjJv31kZDbu2n3DAfxsUxGfws2aHD4
  template:
    metadata:
      name: grafana-mcp-credentials
      namespace: monitoring
