---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-mcp
  namespace: monitoring
spec:
  releaseName: grafana-mcp
  interval: 1h
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
      interval: 60m
  dependsOn:
    - name: kube-prometheus-stack
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Grafana MCP Server container image
    # Note: As of the implementation date, the official grafana-mcp image may not be published
    # You may need to build the image from https://github.com/grafana/mcp-grafana
    # and push to a custom registry, then update the image reference below
    image:
      repository: ghcr.io/grafana/mcp-grafana  # {"$imagepolicy": "flux-system:grafana-mcp-policy:name"}
      tag: "latest"  # {"$imagepolicy": "flux-system:grafana-mcp-policy:tag"}
      pullPolicy: Always

    # Resource configuration
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Grafana connection configured via sealed secret
    vars:
      # Transport mode: sse (Server-Sent Events for web clients)
      TRANSPORT: "sse"
      # Enable debug logging (set to false for production)
      DEBUG: "false"

    # Environment variables from sealed secret
    secretVars:
      GRAFANA_URL: grafana-mcp-credentials
      GRAFANA_SERVICE_ACCOUNT_TOKEN: grafana-mcp-credentials

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
      readOnlyRootFilesystem: false  # MCP server may need write access for temp files
      capabilities:
        drop:
          - ALL

    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534

    # Service configuration
    containerPort: 8000

    # Ingress configuration (Tailscale)
    ingress:
      annotations:
        tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
      ingressClassName: tailscale
      host: grafana-mcp
      path: /
      tlsEnabled: true
      tls:
        - hosts:
            - grafana-mcp

    # Health check endpoint
    probe:
      enabled: true
      path: /healthz
      settings:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3

    # Liveness probe
    livenessProbe:
      enabled: true
      path: /healthz
      settings:
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3

    # Readiness probe
    readinessProbe:
      enabled: true
      path: /healthz
      settings:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3

    # Single replica for MCP server
    replicas: 1

    # Pod labels for monitoring
    podLabels:
      app.kubernetes.io/name: grafana-mcp
      app.kubernetes.io/component: mcp-server
      app.kubernetes.io/part-of: monitoring

    # Service labels
    serviceLabels:
      app.kubernetes.io/name: grafana-mcp
---
# ImageRepository for automated image updates
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: grafana-mcp
  namespace: flux-system
spec:
  image: ghcr.io/grafana/mcp-grafana
  interval: 24h
---
# ImagePolicy for automated image updates
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: grafana-mcp-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: grafana-mcp
  policy:
    semver:
      range: '>=0.1.0'
  filterTags:
    pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
  interval: 24h
