---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-mcp
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana-mcp
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  dependsOn:
    - name: kube-prometheus-stack
  values:
    # Official Grafana MCP Server image
    image:
      repository: grafana/mcp-grafana  # {"$imagepolicy": "flux-system:grafana-mcp-policy:name"}
      tag: ""  # {"$imagepolicy": "flux-system:grafana-mcp-policy:tag"}
      registry: docker.io

    # Grafana connection configuration
    grafana:
      url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
      apiKey: ""  # Set via GRAFANA_SERVICE_ACCOUNT_TOKEN from sealed secret

    # Environment variables from sealed secret
    # The sealed secret contains only:
    # - GRAFANA_SERVICE_ACCOUNT_TOKEN: <service account token from Grafana>
    envFrom:
      - secretRef:
          name: grafana-mcp-credentials

    # Resource configuration
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Ingress configuration (Tailscale for private access)
    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
      hosts:
        - host: grafana-mcp
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - grafana-mcp

    # Pod labels for monitoring
    podLabels:
      app.kubernetes.io/name: grafana-mcp
      app.kubernetes.io/component: mcp-server
      app.kubernetes.io/part-of: monitoring
---
# ImageRepository for automated image updates
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: grafana-mcp
  namespace: flux-system
spec:
  image: docker.io/grafana/mcp-grafana
  interval: 24h
---
# ImagePolicy for automated image updates
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: grafana-mcp-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: grafana-mcp
  policy:
    semver:
      range: "*"
