apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unmonitorr
spec:
  releaseName: unmonitorr
  chart:
    spec:
      chart: ./charts/onechart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: unmonitorr-helm-values
      optional: true
    - kind: ConfigMap
      name: unmonitorr-image-auto
      valuesKey: values.yaml
  values:
    vars:
      PLEX_PORT: 9797
    existingSecrets:
      - name: unmonitorr
        optional: true
    containerPort: 9797
