---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    apiToken: AgCI3Tl77a7VJA/KXCF8r+Iy8cSwgqdO6FsGr1teFSVMi/EtNG6HxtpHP/pIuuBUSdaHq5PJmCCzTF62kKuyFpELowFzkeLffAtdBLEj4Wh1d+Q83NWhOr359+9qF7T1CiBY2Bokh1Ar47qRzO1/oOif2Vl+z/mT5E8wUQ6/QDm/oyITvxVX10WojT/cZU3IKK069X30D07DUZ51qPeNG0QbuIIIbuL2SFOaTE+5YC9Ffyjv6bEPlnjw0rSuD1fPkVB22/OuQTpmYiC6Bo+WKxOEf1JfxjTk8vSg0ueFzrcOCrBrVvw235t3FYCFvGCXGs2jmvNj4fTKXu/RDXGAJdB51Mf8viMdfuBG8GY2VoRNnif7sh55H1+Mb5ODXNe1Z67UozxMY5LIIQiwm51itu/pOy/0CdCWfMh6gKHRCicooMycPYx17q3sU1GQc+haUSy5c4A6A5gFOSkHKObShVhSRgzNe/oJq++MmgCaQ5OLFsxSYvyLP32hN8KGCOWo98NWWpcMCkC6tJiJiSaRCV/baLZg3mOni/wuWCjraZ1dnh1PspBqaNcNfudEZoQDY+EQovCNK95tzSN1SsBEDjwWM8dIUr4wvFCvT+dngMh6xfJIf3N+nxjLjasu2DOoPka6JY6HZDEr39LhOlaBbd4LKurLfXJgRe3q2Vw4S0jGFBF4J4NoTpj/9afjZ6n0CMwtpwnOzB+aJkdqe2rjzwrnJF75uf9DwjKB0i8YjQg/mI5WoXCYp5TvH/Jdea17bosn7qq9lg==
  template:
    metadata:
      name: external-dns-cloudflare-secret
      namespace: external-dns
    type: Opaque
