---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-operator-secret
  namespace: flux-system
spec:
  encryptedData:
    oauth-client-id: AgAgNyxHyeb1WdosYYS7Ctl9gR16hRW9k0u7OPYytdIzFi5UL+Q88sJKYKMaQR/smjVEAeaWt8Dity6A6d3XBu6rXwJUt7l4cMQr8I6ygdX36uHj2GYMx+trrlB14KCC2oTgSvaQ08tb2Cqjp1GGvae8tCSaqPaP9yWHga1hy0ptDLqW4/8aPJeEcYXDWDJAQihWqVBs1kWS8yZTG8cVuTOTuP2TR9Timdc6JRB3vR7adZH7j2KwOAsVKH519M7UwYwXPKBcMvPtHqbcRTlQWvAEK3XdFeA29a6KggCERL58VrVakU8BbtlQFx43zgaBY3Jz313FxMgwS0LAiimGF//FV/12ir8JQTLYQadQ/jylvnPXsyBCNaG3EpMXvyfbe+RQY5Wrx0CjIj3DFNmlfanHhmnimcZGDVipc/JIY/ihr+an+7dWLbCn6mRKIfuzp3uweDzLiQmdmhSjl3XKexiMYK9u4lQrp0S71rlcFcePjW+A2FyoM8t1A3hmASNDMDUSPXVYfaoYk1u7fAj7qxxfV3fsozV1EVUq8St3vOzgPQx/8HVLlq+uJQvGWzrOZWNnSaeqZoTWVojD8wlFkin0qdZJ0z5jOswOUbVrI/FwthuWacIpzFm/uRwMh4gTBvmZjdE4HAru7eYHpbmgIo8Hf9sM297EpnoY0uG3mUJwk3KTfnvYYWjafZfeXGE4kv7JzJmYBIsBlheBhAmK0XOo+w==
    oauth-client-secret: AgCz7wWFVaDQTZndmZu5f2re0qMz90c02Nw9GM5k383+ej0OJrY9oxFIXrRDl5be2YzeMDQGwAF4A7h8W8N6+Lo74Lt1ySATMW8bvVYpTmtB1EClxZL+CmCdiX/g+6yR9tW5VhOm+6UZ5O4G2UMqNKbsmd8mtzCGSu0euw405OnwmtFJ/IEdHs/BVww1rKsgDSZ6wG19XD4Eu61+ZD0xqSXa896sxxcN37sStITyGGYtwHxKgU7o08YRe8WwpOwnwchCa3ii9VQRNfyNrYynBdjqkSvgl/T1kdREn5kICzlnaC29qzqDVfhNmOuwwPQjtXlrOyg1V38/VwQvw3/+1Qu/3gsbyuffMPo0GWfd10kKZCFFidfM5H/P84l/Nw4aFq4yrPK6nZ0ZFXPRPoOf/jA1JYABN/V6rpRiSzp4UvFZ3MlhbInHrKhcJ3ibZHFdFyxVe2JkEEbxQGFnjT9Q2j9oEbO2eUZnJEpIyDneRArHh+MbYRB5SfsJDPptQWH5BXt79KFuQFpl7Qr0MBbqdfRqHgrdMWxsNImyOLYtw8A12o2xWjeW2rxHiQyafgQf/+Po5OoIkybY1YQPd4MN5Ch+fQRLCETLgTrT/0/jTigD3EfhM3Vj1hBhLe8XDikYMYxkU+FGYHFSQg6ieu0Tf+B+uY7AiWQhgfLGdWkNgRdTjm+HrEn5Qn+O00R22PyW2AhyjQSI8Mk4GmNO6CfDQVg5I7CKjOdJiMHijcZOP6Vl4g/rGz6/j4Na78Kx4uUWiz+/dampfTgdHEcjsBLjWwPz
  template:
    metadata:
      name: tailscale-operator-secret
      namespace: flux-system
    type: Opaque
