---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsidp-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgBe5ds6CiMco2/6MNu0OCShndN73BkPx9KM4wvUWJc+pWVJIft04p98SC4Sfs1V7oI1MWJIh3yvzcoaPCyahzHd8i4+EONi8h7OHVeuOXY5H0efHnK6tDXXYbHhqUbmM/Kieh1VrXwT5yCtg/BmSSrKGzi/jKVY2XRKkYqsPHjOO6PMIM/5JJxTzaNfpZQNn+1VMWqFGFECZNCzPHvkrwzBLSVgtBj2P/56KeZIkKvVQyzREec3g79q8O0aW5Gr79qj9Ucv6HGJrGJo3P3gkfQMu5zflWEaR1TKZkmC/1zuncCs/buBCvX6/DKrxG9KGsZo6GTiaWwjR7n5MUMQfCqlYUJ2MM8CivaGCMm1Ko+46Vq4s0hiFBronUt1MwNK1alrsCANRrR5ZzjOj43k9I3PMdATxHT00v4spC+3kZY2o+82F0SPUbbJRINFrgu3zEiYoTcM0DkoznZKynaBqb1OXhia9xsyYH9h2IHCKxlTFGFomcoODxNT5EOFIuNhVHfzBsbg5ytS+vHRk26WxMwie9mGNVA+7XV3ZrC/Zksub7x35VuhBd0/vLhal69rTrz9iPdV1H3erhTVI1f8ibEL10vFiUyXA49cy1mUKgt5Wkr3CWzhHycshf5y849eYiB0/i9Wnq0xanXvPw4Kd2dOVA9WKCv3B2SzipdF2lxprrm5tpylnarQAuwY+eCj6TPBXv9iR8IAhQ3qs/qVvqaDBHG7+ZxFSE8T5PhJ6a1eMCSxdtTVtqxl4D9DEYuq9tuervuBcnmvjU4sbNiLWZ4=
  template:
    metadata:
      name: tsidp-auth
      namespace: tailscale
