apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base/arkham
  - ../../base/bazarr
  - ../../base/jellyfin
  - ../../base/lidarr
  - ../../base/overseerr
  - ../../base/pihole
  - ../../base/plex
  - ../../base/prowlarr
  - ../../base/qbittorrent
  - ../../base/radarr
  - ../../base/sonarr
  - arkham-unmonitorr-sealed-secret.yaml

patches:
  - path: arkham-resources.yaml
  - path: arkham-pihole-patch.yaml
    target:
      kind: HelmRelease
      name: pihole
      namespace: arkham
