apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arkham

resources:
  - namespace.yaml
  - pvc.yaml
  - ../../base/apprise-api
  - ../../base/bazarr
  - ../../base/configarr
  - ../../base/flaresolverr
  - ../../base/jellyfin
  - ../../base/lidarr
  - ../../base/msmtpd
  - ../../base/overseerr
  - ../../base/pihole
  - ../../base/plex
  - ../../base/prowlarr
  - ../../base/qbittorrent
  - ../../base/radarr
  - ../../base/sonarr
  - ../../base/tautulli
  - ../../base/unmonitorr
  - arkham-unmonitorr-sealed-secret.yaml

patches: []

configMapGenerator:
  - name: apprise-api-helm-values
    files:
      - values.yaml=apprise-api-values.yaml
    options:
      disableNameSuffixHash: true
  - name: bazarr-helm-values
    files:
      - values.yaml=bazarr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: configarr-helm-values
    files:
      - values.yaml=configarr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: flaresolverr-helm-values
    files:
      - values.yaml=flaresolverr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: jellyfin-helm-values
    files:
      - values.yaml=jellyfin-values.yaml
    options:
      disableNameSuffixHash: true
  - name: lidarr-helm-values
    files:
      - values.yaml=lidarr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: msmtpd-helm-values
    files:
      - values.yaml=msmtpd-values.yaml
    options:
      disableNameSuffixHash: true
  - name: overseerr-helm-values
    files:
      - values.yaml=overseerr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: pihole-helm-values
    files:
      - values.yaml=pihole-values.yaml
    options:
      disableNameSuffixHash: true
  - name: plex-helm-values
    files:
      - values.yaml=plex-values.yaml
    options:
      disableNameSuffixHash: true
  - name: prowlarr-helm-values
    files:
      - values.yaml=prowlarr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: qbittorrent-helm-values
    files:
      - values.yaml=qbittorrent-values.yaml
    options:
      disableNameSuffixHash: true
  - name: radarr-helm-values
    files:
      - values.yaml=radarr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: sonarr-helm-values
    files:
      - values.yaml=sonarr-values.yaml
    options:
      disableNameSuffixHash: true
  - name: tautulli-helm-values
    files:
      - values.yaml=tautulli-values.yaml
    options:
      disableNameSuffixHash: true
  - name: unmonitorr-helm-values
    files:
      - values.yaml=unmonitorr-values.yaml
    options:
      disableNameSuffixHash: true
