apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/arkham
  - arkham-unmonitorr-sealed-secret.yaml

patches:
  - path: arkham-resources.yaml
  - path: arkham-pihole-patch.yaml
    target:
      kind: HelmRelease
      name: pihole
      namespace: arkham
