resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "4"
    memory: "4Gi"
ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: arkham-strip-prefix@kubernetescrd
  host: arkham.${ts_net}
