resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"
ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  host: arkham.${ts_net}
