---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
  install:
    createNamespace: true
  interval: 10m0s
  targetNamespace: tailscale
  values:
    oauth:
      clientId: k1FnJf3pDp11CNTRL
    apiServerProxyConfig:
      mode: true
  valuesFrom:
    - kind: Secret
      name: tailscale-operator-secret
      valuesKey: oauth-client-secret
      targetPath: oauth.clientSecret
