---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-operator-secret
  namespace: flux-system
spec:
  encryptedData:
    oauth-client-secret: AgCP2NQi1DmzU/52NitV6Cf+edbL9IVIjcZrzCp0m6EFRdvf2yuCEXERkSPeZrfu4cxCUuSuVHdy80iAaYqbNMIOi3vWKIiTANFvHVVBXa4yR+SH4FjbgLCvJpSYKZSJEWnY2nF5O0h5Rphd9/4ymPraygQk/vAxvvtEcvEf3RE9Ax8NlTOcioYN9H7e2jlhJH1LZSNVBzDduTJOKjenmLydM3FaMA4qNtQc5hNE6y/nM5I/YHXt3bWFINd3NedU7t1tJOQIzVLA9f/LIsT3uJ9bj8irVDfjiycL/n1728Clxhxtn1itJd5eFh8GgHRbEIZp+fFhkt6R93CrY6p6nmtBOld1xtJgTghTaoNk6rXLbW7Ct7wPr1HQ0ChD6DbCDc4AQ+VzMG8KETtQ/9Rk6oLjTuN2N2pcobDKjv6FnEC7QZEkYY4IRKMcW96mBaQXaj6t7LW2iXmp3gAaMlHkbfGoUijo0jAGlBpQnXKW3JwL0k2upmStTwSMoir/dh7f9HO+CqPSDg6rs7dcgx992N/zNGAUjbYn9YeCdIcuzSN0xyyi/hMZCbUqk+jcdsq1TJIGoZBVOMI+vHrKStDw0yyc1V66NwaEuHuZFZrRRq4URBWLfC70aE2QLLAazY52kPmkK2XDqkD7rlqhgddqVwOA62k16h3FmJ1DVnC+NVbvqMln2fp60s9IIlYCrRxNsP0YDt5eAdbbCVFxkYhCWntSMg03MwgBd6PgUy1MuaaZRR6ZFmp7RmRzXYBfORZfxWH+pkfpTEceWDT5rKEDcLg=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-operator-secret
      namespace: flux-system
