apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - arc-runner-set.yaml
  - coder-runner-set.yaml
  - copilot-runner-set.yaml
  - fission-runner-set.yaml
  - raiplaysoundrss-runner-set.yaml
