apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - sealed-secrets.yaml

configMapGenerator:
  - name: librechat-config
    namespace: ollama
    files:
      - librechat.yaml

configurations:
  - kustomizeconfig.yaml
