---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otwld
spec:
  type: default
  interval: 24h
  url: https://helm.otwld.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: otwld
  interval: 12h
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: ollama-helm-values
      valuesKey: ollama-values.yaml
      optional: true
  values:
    ollama:
      models: {}
    ingress:
      enabled: true
