apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: otwld
  interval: 12h
  values:
    ollama:
      models:
        pull:
          - gpt-oss
          - deepseek-r1
      
    ingress:
      enabled: true
      className: tailscale
      hosts:
      - paths:
          - path: /
            pathType: Prefix
      tls:
        - hosts:
            - ollama
