apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: otwld
  interval: 12h
  values:
    ollama:
      models:
        pull:
          - gpt-oss
          - deepseek-r1
      
    ingress:
      enabled: true
      className: tailscale
      hosts:
      - paths:
          - path: /
            pathType: Prefix
      tls:
        - hosts:
            - ollama
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librechat
  namespace: ollama
spec:
  releaseName: librechat
  chart:
    spec:
      chart: helm/librechat
      sourceRef:
        kind: GitRepository
        name: librechat
  interval: 12h
  values:
    librechat:
      configEnv:
        NO_INDEX: "true"
        ALLOW_EMAIL_LOGIN: "false"
        ALLOW_REGISTRATION: "false"
        ALLOW_SOCIAL_LOGIN: "true"
        ALLOW_SOCIAL_REGISTRATION: "true"
        ALLOW_PASSWORD_RESET: "false"
        ALLOW_ACCOUNT_DELETION: "true"
        ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"
        DOMAIN_CLIENT: https://chat.${ts_net}
        DOMAIN_SERVER: https://chat.${ts_net}
        GITHUB_CALLBACK_URL: /oauth/github/callback
      existingConfigYaml: librechat-config
    ingress:
      enabled: true
      className: tailscale
      hosts:
      - paths:
          - path: /
            pathType: Prefix
      tls:
        - hosts:
            - chat
