---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  image: ghcr.io/n8n-io/n8n
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: n8n-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: n8n
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 24h