---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 24h
  targetNamespace: n8n
  sourceRef:
    kind: GitRepository
    name: n8n
  path: "./kubernetes"
  prune: true
  timeout: 5m

  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/envFrom
          value:
            - secretRef:
                name: n8n-secret
            - configMapRef:
                name: n8n-config
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: ghcr.io/n8n-io/n8n:latest # {"$imagepolicy": "flux-system:n8n-policy"}
      target:
        kind: Deployment
        name: n8n
        namespace: n8n
