apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: raiplaysoundrss
spec:
  releaseName: raiplaysoundrss
  chart:
    spec:
      chart: ./charts/onechart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: raiplaysoundrss-helm-values
      optional: true
  values:
    image:
      repository: ghcr.io/alecsg77/raiplaysoundrss # {"$imagepolicy": "raiplaysoundrss:raiplaysoundrss-policy:name"}
      tag: "0.7.5" # {"$imagepolicy": "raiplaysoundrss:raiplaysoundrss-policy:tag"}
    imagePullSecrets:
      - regcred
    containerPort: 3000
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      host: rss.${DOMAIN}
