apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: raiplaysoundrss
  namespace: raiplaysoundrss
spec:
  releaseName: raiplaysoundrss
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 10m
  values:
    image:
      repository: ghcr.io/alecsg77/raiplaysoundrss # {"$imagepolicy": "flux-system:raiplaysoundrss-policy:name"}
      tag: "v0.7.0" # {"$imagepolicy": "flux-system:raiplaysoundrss-policy:tag"}
    imagePullSecrets:
      - regcred
    containerPort: 3000
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt
      tlsEnabled: true
      host: rss.${DOMAIN}
