---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-alecsg77-regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBigRowIuK8x0Yk2gIo22gJjB8PFnk6s6ybad7ZemlUxaGxBCjxTvax5ckIJllUog/WpySL6/Cw/u2tlnpdf3YU90SERqMLjVnqJeLJv0i8ZEzCvHniSsSnxk2fKxOl/DJAqUFfNyftSCairpPrsQRkaY7gT37sq60z9Huokmm1qUaVMKOOsnxRE8FAEi0Vku0I87jEy9m4XghY5vhYOrpMD6/JQTXd0EAzR9PPatd66KB08rRr1TaYjFiE6bJzJ3K6ROW8NstrCaNpWpCwb6ozdwfyrtpY/bxpGG4Mf/rJJrrtL3vOQ6vuyOhtO2uaySur6Z4xk8jgZor8Z62Pf7d/65b26zeINwHQQxVsWKc642/pv2nsDVFfgP/3Od9yv4cWvvIaeFA9ouPj4iqqm3HUxHwCt+QsEA6ePBrQZFLy1L37KSylJm1GIYCyg4fzCTM56GLzPXS7B1FnjOKty1wAGPdmae2obO0LWVq5hdmmtLK5mY2kDtkVqUG0SJttAruEH6h3hq/hOpJo/W6lQRLmOmyUE2rxkU7EaGesromyeehz/o8PZOal2+tLxOpPsAQkpTmGVnM4VVe+WtAAsurJmJW5GAFHZxyIjjyoLXt/hnHy/jszKFVQhBw1YRDYFBbo9Fa4vMbltulIZ1dUV9yOnePLd9CRABlVAIf4J+UV3oiuOgn2DvyCLhWKvKMfwIQlx03AY1X7sFW5ED5XO5tS+UTuU5BptL9/W4hU5zKaEBT87q3brXkarjdk1OQUBRVcxEVIxAl93EC4VcoJa3HmCiKxsR2uRVDMz/NUuRrukpFDFNdcnEsXGTKagNyHK8OOOpY+pYmyjEmDpidsLpdMN3uEVimb6l8r+/rcG0TB6ZFXMVT4fzfdFjp0OPXpiMxL6StG1PDxnRclbJP2Gw635YgMcmL35rU20Mjm/zqsm9NlxI3m4Dw9/R9mbxXA1pbOxV9VBCKVBtKjzhJDfVVtA1Matg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-alecsg77-regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: raiplaysoundrss
spec:
  encryptedData:
    .dockerconfigjson: AgBigRowIuK8x0Yk2gIo22gJjB8PFnk6s6ybad7ZemlUxaGxBCjxTvax5ckIJllUog/WpySL6/Cw/u2tlnpdf3YU90SERqMLjVnqJeLJv0i8ZEzCvHniSsSnxk2fKxOl/DJAqUFfNyftSCairpPrsQRkaY7gT37sq60z9Huokmm1qUaVMKOOsnxRE8FAEi0Vku0I87jEy9m4XghY5vhYOrpMD6/JQTXd0EAzR9PPatd66KB08rRr1TaYjFiE6bJzJ3K6ROW8NstrCaNpWpCwb6ozdwfyrtpY/bxpGG4Mf/rJJrrtL3vOQ6vuyOhtO2uaySur6Z4xk8jgZor8Z62Pf7d/65b26zeINwHQQxVsWKc642/pv2nsDVFfgP/3Od9yv4cWvvIaeFA9ouPj4iqqm3HUxHwCt+QsEA6ePBrQZFLy1L37KSylJm1GIYCyg4fzCTM56GLzPXS7B1FnjOKty1wAGPdmae2obO0LWVq5hdmmtLK5mY2kDtkVqUG0SJttAruEH6h3hq/hOpJo/W6lQRLmOmyUE2rxkU7EaGesromyeehz/o8PZOal2+tLxOpPsAQkpTmGVnM4VVe+WtAAsurJmJW5GAFHZxyIjjyoLXt/hnHy/jszKFVQhBw1YRDYFBbo9Fa4vMbltulIZ1dUV9yOnePLd9CRABlVAIf4J+UV3oiuOgn2DvyCLhWKvKMfwIQlx03AY1X7sFW5ED5XO5tS+UTuU5BptL9/W4hU5zKaEBT87q3brXkarjdk1OQUBRVcxEVIxAl93EC4VcoJa3HmCiKxsR2uRVDMz/NUuRrukpFDFNdcnEsXGTKagNyHK8OOOpY+pYmyjEmDpidsLpdMN3uEVimb6l8r+/rcG0TB6ZFXMVT4fzfdFjp0OPXpiMxL6StG1PDxnRclbJP2Gw635YgMcmL35rU20Mjm/zqsm9NlxI3m4Dw9/R9mbxXA1pbOxV9VBCKVBtKjzhJDfVVtA1Matg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: raiplaysoundrss
    type: kubernetes.io/dockerconfigjson
