---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  values:
    coder:
      service:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "coder"