apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/coder
  - ingress.yaml

patches:
  - path: coder-values.yaml
    target:
      kind: HelmRelease
      name: coder