apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/coder

patches:
  - path: coder-values.yaml
    target:
      kind: HelmRelease
      name: coder
  - path: coder-logstream-kube-values.yaml
    target:
      kind: HelmRelease
      name: coder-logstream-kube