---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    control-plane-endpoint: AgBZcXbPhFA2RuvudXh8HNoErvdnnWdqBHSnaywWmcBIW5CD3EoLML+5mCffw+gLpOiFYEZmu9MKkHYKrI+hx0qouGcggoqhCC8TOY0k7roryfOFeOxZ1tw2JLsFOc51i71lFf504588FA9JaSzKThyNjwOhgKXzX/78priZ3PruiA/F8omTCGPjwZcuyv/tzjYEB1ne2aEosB2KjY4vlTF5wkcQottes4uyd1CSmt0AdFXF2e9VSpsz2v+Yr7OJW6uD25/lArCV1rf/ETENmV8GHNmh1jO6hWEKhCsWg552AAgq8MMpHT720wqf6WfsTPjzeIDqYcLPyU6UDcydBr7hJIaHYfUfIyiVNEV7hgT+WUmJUfnNmbMyHPve/gqItyibTiLm24TkTisoVIhk+ywjnl2H+AdC0Cp3t09nyL08B4us4JqzzGt0qjuXx1fDKuNCvww7j3msNgZBo2OhbwIu7scXxD2+t8jjVdyMnCKNEwFEq7CslOzg2/bxQmTy5wCXvnw8c9JnFcMLWXGE8qERz8YTv6JYOqFTjSL7JCnrnxpHJ//6s6pOMX8rWyexqKJLDzPGERL4tqnXyxwLokRkmoz80EjBxdDcOiBOtCvh3qTyjeIc6lhiElu4gtlC83BGhNBfawgDtbhBG30z/c4M4lF1m0JF4df2ynJFc4YSgPLmVme1bQ4pEwkqnbwffwz3JTIbZBvyvn4PI2seeA==
  template:
    metadata:
      name: kube-prometheus-stack-values
      namespace: monitoring
    type: Opaque
