apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 5m
  dependsOn:
    - name: loki
  chart:
    spec:
      version: "1.x"
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
