---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  image: linuxserver/qbittorrent
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: qbittorrent-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: qbittorrent
  policy:
    semver:
      range: 5.x
