name: ✨ Feature Request
description: Suggest an enhancement or new feature for the Elysium cluster
title: "[Feature]: "
labels: ["enhancement", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        
        Thanks for suggesting an improvement! Please provide details to help us understand and prioritize your request.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of enhancement is this?
      options:
        - New Application/Service
        - Monitoring/Observability Enhancement
        - Networking Improvement
        - Security Enhancement
        - Performance Optimization
        - Developer Experience
        - Documentation
        - Infrastructure/Platform
        - CI/CD Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High (Critical for operations or blocking workflow)
        - Medium (Would significantly improve experience)
        - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point does it address?
      placeholder: |
        Describe the problem or limitation:
        - Current limitations
        - Manual workarounds needed
        - Missing capabilities
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        Describe your ideal solution:
        - New services to deploy
        - Configuration changes
        - New workflows or automation
        - Infrastructure improvements
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered alternative approaches?
      placeholder: |
        Other solutions you've thought about:
        - Alternative technologies
        - Different architectural approaches
        - Workarounds being used currently
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Improved performance
        - Better reliability
        - Enhanced security
        - Easier maintenance
        - Cost savings
        - Better user experience
    validations:
      required: false

  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Technical details or requirements for implementation
      placeholder: |
        - Required dependencies
        - Configuration requirements
        - Resource requirements (CPU/memory)
        - Integration points
        - Flux/GitOps considerations
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete and working?
      placeholder: |
        - [ ] Specific functionality working
        - [ ] Tests passing
        - [ ] Documentation updated
        - [ ] Monitoring configured
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant documentation, examples, or discussions
      placeholder: |
        - Project documentation
        - Similar implementations
        - Related discussions
        - Helm charts or examples
    validations:
      required: false

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Links to related issues or feature requests
      placeholder: "#123, #456"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
      placeholder: Add any other relevant information, diagrams, or examples
    validations:
      required: false
