---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  image: linuxserver/plex
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: plex-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
  policy:
    semver:
      range: 1.x
