apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: arkham
spec:
  releaseName: plex
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 10m
  values:
    image:
      repository: linuxserver/plex # {"$imagepolicy": "flux-system:plex-policy:name"}
      tag: "1.41.3" # {"$imagepolicy": "flux-system:plex-policy:tag"}
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
        gpu.intel.com/i915: "1"
      limits:
        cpu: "8"
        memory: "8Gi"
        gpu.intel.com/i915: "1"
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
      VERSION: docker
    volumes:
      - name: storage
        size: "100Mi"
        path: /config
        subPath: plex/config
        existingClaim: pvc-storage
      - name: library
        size: "100Mi"
        path: /media/library
        existingClaim: pvc-library
      - name: tmp
        size: "10Gi"
        path: /tmp
      - name: storage
        size: "500Mi"
        path: /backups
        subPath: plex/backups
        existingClaim: pvc-storage
    containerPort: 32400
    probe:
      enabled: true
      path: /identity
      settings:
        initialDelaySeconds: 10
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /identity
      settings:
        initialDelaySeconds: 15
        timeoutSeconds: 10
    podSpec:
      hostNetwork: true
    container:
      ports:
        - name: http
          containerPort: 32400
          hostPort: 32400
