apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
spec:
  releaseName: overseerr
  chart:
    spec:
      chart: ./charts/onechart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: overseerr-helm-values
      optional: true
  values:
    image:
      repository: lscr.io/linuxserver/overseerr # {"$imagepolicy": "arkham:overseerr-policy:name"}
      tag: "version-v1.35.0" # {"$imagepolicy": "arkham:overseerr-policy:tag"}
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
    podSecurityContext:
      fsGroup: ${PGID:=1000}
    volumes:
      - name: config
        size: "100Mi"
        path: /config
        subPath: overseerr/config
        existingClaim: pvc-storage
    containerPort: 5055
    probe:
      enabled: true
      path: /api/v1/status
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /api/v1/status
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 10
    ingress:
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: overseerr
spec:
  image: lscr.io/linuxserver/overseerr
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: overseerr-policy
spec:
  imageRepositoryRef:
    name: overseerr
  filterTags:
    pattern: '^version-v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$'
    extract: "$major.$minor.$patch"
  policy:
    semver:
      range: 1.x
  digestReflectionPolicy: Always
  interval: 24h
