apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - tailscale-operator-secret-selead.yaml
patches:
  - path: tailscale-operator-values.yaml
    target:
      kind: HelmRelease
      name: tailscale-operator