---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-operator-secret
  namespace: tailscale
spec:
  encryptedData:
    oauth-client-secret: AgCxN6oFSbYCxB4SCgb7/cNm4j8koeTtJbYj+6kG7ldxuipJS138ZrLSC3qRjdLfgoCD5qIInWr1uQqaRzWLJar3VTmZRmjabESsvPBIyrCSC68Pn6yZ+DTgpaF1KvHvzpMk1DsGnF2kg4mJmh/y+jdUYCb1z4fM7OQceBtiKODuDsXFUkoKfEcUYKUGKm3+ldCkmGUqE9E7lBlptjdL1SSx6RO9d6LSBQtRNHytbF4lTL3bgtsgu4LFsaIU97qTaL32zt1f8nHkAHTEejS4Dydn/ZC2VlcvpHPgodeias7lNAZ7ukqK+lCuQUZHVw0962Zre6Po7wO5Idao6KvlwhDJaODR5rB4OOY3fCuyRUhtuJKk4tVVMufLr7sQJYP2NxXsK3McLn768D2vyu+nxfN42bosOwQoI3inAfobKf5P4siLu9ETql1+ds0og8yCiRpm4vTgeLnqdOkYNXBwRDxunDA3yR/qJHK8O1ayzXdcJNGm1l3vrHJAmGD/DuF7ShXjlz79B1XP52GiNrZUTi0X8/WSysfqVBB8I5vv9N2d+zKgePJ79TzeNUHf6N0xH6XX5Dy6uUTxODrYH5DU9+mJhVkOd+aecqGUCn9I3CrIIkutKLsDC2qpkJmseHOmi7iPMH2C7HdJ26DexZmgIM6DGhl4hDpb8Epj4IZb0lbnPldy/iie0PhlDJOMLOXoHm8bTMkGd7RZksAPDgfbCoAGYHh6e6oo+8sfc+hmUx8DpaV557Af2XUtKnBuC/v+WeiAM9Gv9Ape/k86bVqv0Mo=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-operator-secret
      namespace: tailscale
