---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: db
  namespace: coder
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 12h
  targetNamespace: coder
  values:
    auth:
      username: coder
      password: coder
      database: coder
    persistence:
      size: 10Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  chart:
    spec:
      chart: coder
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coder-v2
  interval: 12h
  targetNamespace: coder
  values:
    coder:
      serviceAccount:
        extraRules:
          - apiGroups: [""]
            resources: ["secrets"]
            verbs:
              - get
              - list
              - watch
          - apiGroups: [""]
            resources: ["serviceaccounts"]
            verbs:
              - get
              - list
              - watch
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
        - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
          value: "true"
        - name: CODER_OAUTH2_GITHUB_ALLOW_EVERYONE
          value: "true"
        - name: CODER_OAUTH2_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-oauth2-github
              key: clientId
        - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-oauth2-github
              key: clientSecret
        - name: CODER_EXTERNAL_AUTH_0_ID
          value: "github"
        - name: CODER_EXTERNAL_AUTH_0_TYPE
          value: "github"
        - name: CODER_EXTERNAL_AUTH_0_SCOPES
          value: "repo,workflow,admin:public_key"
        - name: CODER_EXTERNAL_AUTH_0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-oauth2-github
              key: clientId
        - name: CODER_EXTERNAL_AUTH_0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-oauth2-github
              key: clientSecret
        - name: CODER_PROMETHEUS_ENABLE
          value: "true"
        - name: CODER_PROMETHEUS_COLLECT_AGENT_STATS
          value: "true"
        - name: CODER_LOGGING_HUMAN
          value: "/dev/stderr"
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2112"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder-logstream-kube
  namespace: coder
spec:
  chart:
    spec:
      chart: coder-logstream-kube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coder-logstream-kube
  interval: 12h
  targetNamespace: coder
