---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: coder
spec:
  type: "oci"
  interval: 10m0s
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coder-v2
  namespace: coder
spec:
  interval: 10m0s
  url: https://helm.coder.com/v2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coder-logstream-kube
  namespace: coder
spec:
  interval: 10m0s
  url:  https://helm.coder.com/logstream-kube
