---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dns-cloudflare-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAeR3t/AITs9YZCk0H0topT+YnaBvz5ZeqLAgNZfFssC/ygTC8BF1SQpkQvmdhFFMBjk8OovTO313DQN28YyDfh2elZ3E2FGplshzUpOpHXqJlKdpbymjqQQxBNYRKkfGaw1F8UlY7lZygwr+UtDSJmj97L+H9m9npNbEa3h82ax2Epk2Yb74WCX5+zzP8UZDsD31k+7L7ZZroYajHoHdIpgNWNgTFc4G7V+oe1oek/LdbYJuqKqRwbHN7F7TF6/1bnk3b0wY4oOxQG415w07r+QEmmhgB+uvVEC9y063ElRTmXRFdo+baTW/9fLdx+T3P8aODYzwqzp+2sAUuM4bgziKGQYCcyfWxra6xGHQ3wR5gu8TQNzA80Hp8txILqk9Sv6c/SxLX3HGwVZxZOnKtWLtave58wsLx9k0w2I5ghRqyYRrQd9WLdnfMhw6xf6NF5t6p6ESYpw1dg95F0OLKrbszfNZx+g5Er29UAUzYKGQpUi9parfFD3LJ+sZS7ZJS0FqltfGv7D25R8HxU7uTrT1qeO4q8Sja6fWn5CECCPqtnO7wqmhQlAKVfp4vdF8rxROX+DPpa4Fe1Qdh3FubsFSft7ynjefB6j3+mLOlqrhBdSDHgWRnYKEOkcXEVpUUAVvP3NLIqQvmDBF3C7FphpxCKCOJiEGx+WYM93NE6egmeB1HgxKnRK71Y9aAtk//BuepA+vmd5nRMjHoS1JZWYtZJM/RjkwMrRX1GWHySyMpJP5YAriklc7ABjth/nDMj2uRoLg==
  template:
    metadata:
      name: dns-cloudflare-secret
      namespace: cert-manager
    type: Opaque
