---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: copilot-api-secret
  namespace: ai
spec:
  encryptedData:
    GH_TOKEN: AgDAJ+6sRzsYk23JMOSSmivuseMr1NasxJYcoy0ezYpzU0eFmLDvjb0PQ1tm8lCOUNwQkDZb9EPQHdq5InXJcwWKGCHQFQIdp3uAJJCxXw2QyJmzxdgSDUgK8Z3iKuytzAZk6XGNKezJgw7iapay4Dkr+aVAIbo7N9usZLlcAzjzqCJxo+KYeMAXaTyKJwLnYvg1lqENcccMXyFgQa0XuESZvGbL+/CwB9vCvrznCp6oKufTTrjATyEf/aMkcOT/vvOx8XTsrTar3qMnLMXkAbs8ja5IuexEI/G78Y1/wZNG9WBQ0juBO+vPBjI+/d/TvS6Doyc7mNs4GHqkd4pshM/p+fM1HhdVG5pGuW9XkIt/xwZz4vgVIn1GXgBxvQfnUG7cBOOJbnbVbyj9kJJC1sNkHO/RLBA7OizjLlalHJ3qQr0lR0R0nVtv6QxcRmOHgVH3rBaKm3y2B6n+22z87N49xixP/5nv70F+uO5SckJbjJVQzpjbOMGZu2hGAHpN+hVTmVrw8vOzP9RBbMBIXQU9MPSkjyXyPvOO4QS82MI1Oyencr5RdynAQ5/9R3744+sfKe8fjBrFijYW3bK3K+9Olnk8ktYMIiiud24WofeukN8qstMWAbiy+kbocX5GyzaVUCwDpzV4UEm8V5FDUnIA9VJtRtC8FWachuTEpeu8F3CZj55gAdz1xbGwB4vjDPd5uxju/pksAoonF/7NmTQxGjD3mpjrXJYv8cCKtR2xBFU0XuKK7Qdz
  template:
    metadata:
      name: copilot-api-secret
      namespace: ai
