apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base/ai
  - openclaw-ingress.yaml
  - openclaw-sealed-secret.yaml
  - openclaw-copilot-auth-secret.yaml
