apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - namespace.yaml
  - ../../base/copilot-api
  - ../../base/local-ai
  - ../../base/openclaw
  - copilot-api-sealed-secret.yaml
  - openclaw-ingress.yaml
  - openclaw-sealed-secret.yaml
  - openclaw-copilot-auth-secret.yaml

configMapGenerator:
  - name: local-ai-helm-values
    files:
      - values.yaml=local-ai-values.yaml
    options:
      disableNameSuffixHash: true
