resources:
  requests:
    gpu.intel.com/i915: "1"
  limits:
    gpu.intel.com/i915: "1"
ingress:
  className: tailscale
  hosts:
    - host: local-ai
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - local-ai
