---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-copilot-auth
  namespace: ai
spec:
  encryptedData:
    COPILOT_GITHUB_TOKEN: AgDJRBAF6qDTjwcwGHj43flWTAad3w0kdEI4qWz7Ye5RcjzFJfa5bH0DlAEPavV8p+LuffevK1HACJa72vgGnErCba1AL7NdDkcXzX/1857fdJEKcv1SdzG5iy8v1SQ/5DR8I2ZEKrlCFWWexTYosYbJVUcn+IAjZASCGElNKqQ4P8TK3ZKlXyekl1MaWvpb6BbKwkkPjvsuCfRPQlovKwzWd8bgsSr/7YLXOnDNYNgOH+2+PHhUVBQmvB7kb0BeBeCEe6J2CeHKP3iJltlUd5wIj1Z3l4/Va7lZJDYkGelsaLH6DUFAGnVrHlhoQV8f51kzJL3pVZxYsaUYvdEzDaeWMtSXQcdlMx/TTo/hvoahdZ8517GFa/JYRz+AjgWXEnBne8ux5U96J5uRy7UjGzz54EXUXunwlvkujYnqR8hHny6/w9rZ4DrLrBiwpm/KqZCBE9fl1CtULLrBJ38FaItutB7ZK6TxCdbZC/Wc3VsqDJLIfkSh5H0OY+CcjoU68IfJzggW6nDQEL3BKdQPd++zL1IwLsrcPFjFIzVzsWY+0tyPZy/UGc+UhK9VqeEmq85LRAFZ6wPjNH/bBdxVsJWMV5e7IprQc1DNHdVZjoKT58b/JYmXSL/mJFXosCkOaW3xnavR47lqp5XDWahAQZThmK3lrK1VuIXLSTQ9WxIX1HDvRzhTClRbasym3q5LZ3mrX8DkscaP6aLrCsxndZVS8zZbi6SEWgtLTTBAys1XrKfrWs3NjVFa
  template:
    metadata:
      name: openclaw-copilot-auth
      namespace: ai
