ingress:
  class: tailscale
  host: chat.${ts_net}
  tls: true
sso:
  github:
    clientId: Iv23li9lZj5gR8CHTERs
    clientExistingSecret: openwebui-credentials-env
    clientExistingSecretKey: GITHUB_CLIENT_SECRET
