---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: ai
spec:
  encryptedData:
    OPENCLAW_GATEWAY_TOKEN: AgA8xhJfbJQ+S/S6DSf/+3pqZlTR1ayHxC1aEXiaDhHNsB/MnMpzpGDFfnj3ndd47UbRaINW26Sd+Q/gNNli4W4574uiQY2gAQJZV3an4lnGltHfOk36Si1oImUChQS8m9uE2uafSp7sVjt75ZJF2VA0YJzIQIntNuCTeIGL07rK7eJQaoWsahzu/q1KKGNTdur+bi+RngPaqDNA4J8WAo3aSIqYt1jV92yKWM+wORRp+l9BurgH9LVPM813t0r09kyV5L7Tw0KMILb/sO+AddDiVaVBvWHhke6RAowQ669WDHrUqV9ZYKhmBHQ2rcw6OBZwUQEARGJL6+qi9AjTgBc3svnKkFyRYetzZAH4bvKyLiuEuGAK8zjFC3Lmkj7wqxsYowu52bp+zHER16tHqcWWfRlZuwfkUI1ap9DXb45AcKNia+17J+3QAtOYWM6NfLGQcxgiRN/a9qhiVqoCLRroFkssRi2f/dR/nFbcMKYjPG/s7Htr5iRK1AhFP7EoaxxzOnZUa5hUl6zN3ujzZ74i8Y2EfHYOah5aaKM3mAE4mBI1f4VmwvHMcHywFsafl9k6d9diOEVC4u2v0FT1fd5LkUpCUXwfoceQE4j0KHNmUu2X0Lz748fawfq1/rURcjHWtikhAEG+3w0UEabaGLOAlKzwpHZYoK3s5ZRos6FlOMhJjjHkUYD2TGUA/agB5cRb0/NpEGa79DjMzIE+gRXaS+/9P/ThqcFCRZnNT4tcRYtnQukhtHxn2m/3yEY8XTB9BTbg0fW3dG8tZJ+SgULz
  template:
    metadata:
      name: openclaw-secrets
      namespace: ai
