---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperclip-db-secret-values
  namespace: ai
spec:
  encryptedData:
    values.yaml: AgAqfKgoD2Ug22gbVRfoyFWrTazrDU6R4rMZn7APuwJ4S4nevhQ5/FdH50oMQDnDnZ3AK10hUchfoOwNsBA9glvg68m4acfweuZ39/OS8/UJ2LtyUog3nUF3rFVMwK7dmlOGnPjHtIMOojt6SoibL0NihoxbZ3VNEwiZGLPQlZCTb4WkXpNbXr+r5+pfoZHXa2DfU7hRSykjO46VyeHsQo9XEllTwab/NUdZ7kKJvui65olROKa07OVIhWSlxixCw0qR+WXKfDeFngBbJ+wIA4ryY8punydhvwJ/kZSQyJ4sgfyZ6beMvmmTAnItEi5t5t/Sa8Nmuf/YtIJ7ZaedKztfYeZOL284kGot9jsIuaMKg4pMFi5bPgIfO6jY46elY4RvOBO+EGH6kwWOG7VN5FjOm8ANob/N9fsC/4ubgucdTRCE2XYr5R12nOUR7fNiXiy+TOb3ExI0Wt32maEXe9Yk/8ku1+DBjIzy6GYNr4So4mHgx9BzowUMCgSzTZgrVlINsUwbZCtvWuaKjVsXgbGe7Ov30I3C1bCkJYO/TcH+CJ9PeyQEfo2ISsny7001M+DLlkYxMsJo5Q1OaNCyuTGrpkKdp5oOGRT3KKlMHgXxPKMyjDf3wPNduSHPOKyfWiYciijmz7Sus6gdYCZe7cgg6yW1hgHCbYHoYCsok034x2D3/El4wIo05MoR5FY7pGnhFe2NusVxVsEZ+QsYSPv13kkv44D2Yu4XXcOn1aqyRAXSbM3udPWoeJeLX8IY25isO2uaQS1LRRp6ZFBBubYd4lodJWBQ3puHQNfOFlcOb73goOn0lf4C2ZiTQ8LjfAUqPFO3BaeL7N11LiLQ8Z4pQwj74mmEEbtapsEirOIjvQzU/eVOjbMlqS1SuHcOVfF0lsLhOWTSOsLrmZZa7YtHLI7GQ0A0rCWNvA9p
  template:
    metadata:
      name: paperclip-db-secret-values
      namespace: ai
