---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsidp-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgBerVOzrrTToySjObo3OOQJvUPibxtLS4f7eR/S9x6MOUSMnsABse8J/ue4zSruBOMIj9C1mRLeQVxcMdBH/3Y4fbKPFg5Ta9FkXGqHMf79ZM/XZ4+YrZqgYGNoev67nJsVivNeUT3UOxr1oDTy/NbMwAYRga2bVaj/1TFJTtpO2U+csgj2Qqu+0VItrMcmL9miR73EsME2B1X8CNS8+1L2pYGbrNYwM6JEzsK7o2S/WxSiE/2p1EGbCvkuBF37UmprahjPvZPvhvZP2uPui+F0ReKE2Dck4DQBGL474/2Nbm3gsyqzlLqlPlPuRDL5djjfEw41ofAfIud5xMi9wUesIF25tw/haPmy/e0oU/P3YGd3YpT7jkME2NKCbb7MrESQw/oRitlk5aH1N/3lORX0QY9+IQAu8HeYTYJI+9g65zTRJqe8xSJHJricqUdHWUTVOjgIL1gCb8TBm4age+krcrG6TdAwv7Z0LqrEKyuJJGx98g9WDeIawryry22Bd1DP9vgvI5kL8KZyS89rhtZBUJQ6P+L4Ut78Dw4bujT6tt4VaOnpKz9k7/zncETpVaSGZNVCQSUmLmpuNEPYzZtUDfhDxzY2UCroVr/hLYPIvmaVHUaJdXtUsE46as9W2jNkl5GaG0cRWawauLHSkv4vIW0Plk4L1I2f3VcQB3mNJ8FR7yYImG6EN+lsk5obRVWiOpEoVJoZh3fpsS7gWaLlfjqq3OHO2S/4bLSl2IUFfbb5uV3khc1zaTqoythQc7tzPdPF2bEg5Bwn1XrMog==
  template:
    metadata:
      name: tsidp-auth
      namespace: tailscale
