apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: error-pages
spec:
  releaseName: error-pages
  chart:
    spec:
      chart: ./charts/onechart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: error-pages-helm-values
      optional: true
    - kind: ConfigMap
      name: error-pages-image-auto
      valuesKey: values.yaml
  values:
    vars:
      TEMPLATES_ROTATION_MODE: "random-on-each-request"
    containerPort: 8080
