apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: error-pages
  namespace: default
spec:
  releaseName: error-pages
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: ghcr.io/tarampampam/error-pages # {"$imagepolicy": "flux-system:error-pages-policy:name"}
      tag: "3.8.1" # {"$imagepolicy": "flux-system:error-pages-policy:tag"}
    vars:
      TEMPLATES_ROTATION_MODE: "random-on-each-request"
    containerPort: 8080
