---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: error-pages-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: error-pages
  policy:
    semver:
      range: 3.x
  digestReflectionPolicy: Always
  interval: 24h
