---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set-controller
  namespace: arc-system
spec:
  interval: 24h
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-system
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller
    namespace: arc-system