---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: csi-rclone
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: master
  url: https://github.com/wunderio/csi-rclone.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-rclone
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: deploy/kubernetes/1.20
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-rclone
