---
apiVersion: v1
kind: Namespace
metadata:
  name: inteldeviceplugins-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: inteldeviceplugins-system
spec:
  interval: 24h
  url: https://intel.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dp-operator
  namespace: inteldeviceplugins-system
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: nfd
      namespace: node-feature-discovery
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: inteldeviceplugins-system
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu
  namespace: inteldeviceplugins-system
spec:
  interval: 30m
  dependsOn:
    - name: dp-operator
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: inteldeviceplugins-system
      interval: 12h
  values:
    nodeFeatureRule: true
    sharedDevNum: 10
