apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secrets
  - tailscale-operator
  - https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml
  - system-upgrade.yaml
  - cert-manager.yaml
  - nfd.yaml
  - inteldeviceplugins.yaml
  - csi-rclone.yaml
  - arc.yaml
