apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secrets
  - tailscale-operator
  - tsidp
  - external-dns
  - system-upgrade
  - cert-manager
  - nfd
  - intel-device-plugins
  - arc
  - flux-operator
  - flux-operator-mcp
  - volsync
