---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfd 
  namespace: node-feature-discovery
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfd
  namespace: node-feature-discovery
spec:
  interval: 12h
  chart:
    spec:
      chart: node-feature-discovery
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: node-feature-discovery
