---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 24h
  ref:
    semver: '*'
  url: https://github.com/rancher/system-upgrade-controller.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 12h
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade
