---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 1h
  retryInterval: 5m
  timeout: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  path: ./apps/kyrion
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
      - kind: ConfigMap
        name: cluster-vars
        optional: true