apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
      interval: 60m
  values:
    config:
      metrics:
        port: 9090
    podMonitor:
      enabled: true
