---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: db
  namespace: coder
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m0s
  targetNamespace: coder
  values:
    auth:
      username: coder
      password: coder
      database: coder
    persistence:
      size: 10Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  chart:
    spec:
      chart: coder
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coder-v2
  interval: 10m0s
  targetNamespace: coder
  values:
    coder:
      serviceAccount:
        extraRules:
          - apiGroups: [""]
            resources: ["secrets"]
            verbs:
              - get
              - list
              - watch
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder-logstream-kube
  namespace: coder
spec:
  chart:
    spec:
      chart: coder-logstream-kube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coder-logstream-kube
  interval: 10m0s
  targetNamespace: coder
  values: {}