apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      interval: 60m
  values:
    manager:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true