apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fission

resources:
  - namespace.yaml
  - ../../base/fission

configMapGenerator:
  - name: fission-helm-values
    files:
      - values.yaml=fission-values.yaml
    options:
      disableNameSuffixHash: true
