include:
  - nodejs/openclaw-release-adapter.js
kind: ArchiveUploadSpec
name: nodejs-openclaw-release-adapter-js-xlyJ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: openclaw-release-adapter-c77d87de-32d8-4142-a630-76d3bf480be2
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://nodejs-openclaw-release-adapter-js-xlyJ
  environment:
    name: nodejs22
    namespace: default
  source:
    checksum: {}

---
apiVersion: fission.io/v1
kind: Function
metadata:
  name: openclaw-release-adapter
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 1
  environment:
    name: nodejs22
    namespace: default
  functionTimeout: 45
  idletimeout: 120
  package:
    packageref:
      name: openclaw-release-adapter-c77d87de-32d8-4142-a630-76d3bf480be2
      namespace: default
  requestsPerPod: 1
  resources: {}
