include:
  - package.json
  - openclaw-release-adapter.js
kind: ArchiveUploadSpec
name: nodejs-openclaw-release-adapter-source
rootdir: nodejs

---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: openclaw-release-adapter-6e3e13ad-98dc-4dca-aed0-c3d252a4a554
  namespace: default
spec:
  environment:
    name: nodejs22
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://nodejs-openclaw-release-adapter-source

---
apiVersion: fission.io/v1
kind: Function
metadata:
  name: openclaw-release-adapter
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 1
  environment:
    name: nodejs22
    namespace: default
  functionTimeout: 45
  idletimeout: 120
  package:
    functionName: openclaw-release-adapter
    packageref:
      name: openclaw-release-adapter-6e3e13ad-98dc-4dca-aed0-c3d252a4a554
      namespace: default
  requestsPerPod: 1
  resources: {}
