include:
- nodejs/hello.js
kind: ArchiveUploadSpec
name: nodejs-hello-js-QbgZ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hellojs-3b9061f7-5507-4781-8484-314f7dd90b81
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://nodejs-hello-js-QbgZ
  environment:
    name: nodejs
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2025-06-08T13:53:03Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hellojs
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodejs
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: hellojs-3b9061f7-5507-4781-8484-314f7dd90b81
      namespace: default
  requestsPerPod: 1
  resources: {}
