{
 "title": "Prebuilds",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "template",
    "label": "Template",
    "query": {
     "query": "label_values(coderd_prebuilt_workspaces_desired,template_name)"
    }
   },
   {
    "name": "preset",
    "label": "Preset",
    "query": {
     "query": "label_values(coderd_prebuilt_workspaces_desired{template_name=~\"$template\"},preset_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Experiment enabled?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(coderd_experiments{experiment=\"workspace-prebuilds\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current: Global",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_desired) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_running) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_eligible) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "All Time: Global",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_created_total)) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_failed_total)) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_claimed_total)) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  { "title": "$template", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "template" },
  {
   "title": "Current: $preset",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "repeat": "preset",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_desired{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_running{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_eligible{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "Pool Capacity: $preset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 5 },
   "repeat": "preset",
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_desired{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_running{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_eligible{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "Pool Operations: $preset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 5 },
   "repeat": "preset",
   "targets": [
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_created_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_failed_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_claimed_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  {
   "title": "All Time: $preset",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "repeat": "preset",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_created_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_failed_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_claimed_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  }
 ]
}