{
 "title": "Provisioners",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Provisioners",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder.*`, pod!~`.*provisioner.*`})",
     "legendFormat": "Built-in"
    },
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder-provisioner.*`, namespace=`coder`})",
     "legendFormat": "External"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "Provisioners are responsible for building workspaces.\n\n`coderd` runs built-in provisioners by default. Control this with the `CODER_PROVISIONER_DAEMONS` environment variable or `--provisioner-daemons` flag.\n\nYou can also consider [External Provisioners](https://coder.com/docs/v2/latest/admin/provisioners). Running both built-in and external provisioners is perfectly valid,\nalthough dedicated (external) provisioners will generally give the best build performance."
   }
  },
  {
   "title": "Builds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(coderd_provisionerd_jobs_current) > 0) or vector(0)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(coderd_provisionerd_num_daemons)",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "The maximum number of simultaneous builds is equivalent to the number of `provisionerd` daemons running.\n\nThe \"Capacity\" panel shows the how many simultaneous builds are possible."
   }
  },
  {
   "title": "Build Times",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(coderd_provisionerd_job_timings_seconds_bucket[$__range])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(coderd_provisionerd_job_timings_seconds_bucket[$__range])))",
     "legendFormat": "90th Percentile"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": {
    "content": "This shows the median and 90th percentile workspace build times.\n\nLong build times can impede developers' productivity while they wait for workspaces to start or be created."
   }
  },
  {
   "title": "Build Count Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(coderd_provisionerd_job_timings_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "_NOTE: this will not show the current hour._"
   }
  },
  {
   "title": "CPU Usage Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~`coder-provisioner.*`, namespace=`coder`}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "options": {
    "content": "The cumulative CPU used per core-second. If the process was using a full CPU core, that would be represented as 1 second.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{pod=~`coder-provisioner.*`, namespace=`coder`})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"memory\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "options": {
    "content": "This shows the total memory used by each container; it is the same metric which the [OOM killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html) uses.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{namespace=~`(coder|coder)`, logger=~\"(.*runner|terraform|provisioner.*)\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "options": {
    "content": "This panel shows all logs across built-in and [external provisioners](https://coder.com/docs/v2/latest/admin/provisioners)."
   }
  }
 ]
}