---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    # Replace the email address with your own contact email
    email: ${EMAIL}
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-azure
    solvers:
    - dns01:
        azureDNS:
          clientID: ${dns_azure_clientID}
          clientSecretSecretRef:
            name: dns-azure-secret
            key: clientSecret
          subscriptionID: ${dns_azure_subscriptionID}
          tenantID: ${dns_azure_tenantID}
          resourceGroupName: ${dns_azure_resourceGroupName}
          hostedZoneName: ${DOMAIN}
      selector:
        dnsZones:
        - '${DOMAIN}'
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-azure-secret
  namespace: cert-manager
type: Opaque
stringData:
  clientSecret: ${dns_azure_clientSecret}
