---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dns-cloudflare-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAqwq2zNEUpvedlpGGPWi4bmWJucBDwi14I/zJS6leud/5KnG5eXfcZbj3ouYuQDSrBCO/fRvBdERFlPhz6PodFsFIWhtLj8pgUFPv/OOvk4/iVwJPIUmbrmmqLsIePpv3oUv0vINpYKxfx7vi1RlUphbMEauGOQDzxB4e1URYVx/fvk1Um/bw5TL6gTEw5W6KY5JryuvwwbCJH1rUVk6qIF1AvMy7wnKK7Qopgj1+uyuqFV4t+9mpquOSj8uycBJ53TH+47uF4Tdh+yFjo5/bYI1QLeFZzkTAENkCARIXgTsblO+g+URYzyKMFY0/OesL5FgzfgK2pDT1GohE5Pm6HY5oSRB+/NuiPZFWcfVnvFpRfHM4LgfnBhwOPY6lMPkPKeQWPQ5X2xN7COXfiIWbLTCpdTcGDlfOJC2gKsHEK2lzpkUfv7GPFpH6t0YrN91tAf0KI3VoJOw2X8CDuRZTrrW4QQNZri4wfRJM0mQRq7IqtWc1oUmvRKMMi2xHG1dYQFz+h6tsJzIhTcgJtOZOkOWuUcDwRjXbrpf3/j9ux65vSS9GGcD7XmsIPUPhVy+80ZgVymltD6psXgraOtHpFNCWgeT8V7Vj6xmxMvfHRoXb2me0qWTT6QG+g/CWiaJOWuVRCy8/I7L/HS/Fn7yElGOK+dOTj7iIWwRalbEqeR+6FAzwsO4rnj1T6niMRXx3z9f+vpH6d+MaoAbq+sNJYbkgaUA96ct/GNZ5LiLFuKZ1RuWsKslou
  template:
    metadata:
      name: dns-cloudflare-secret
      namespace: cert-manager
