---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dns-cloudflare-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAX0wP42xrBxnpFO9jaD61DVjaTrnSt4MTTVKtEmRmvqDcEoBy9cpeT8tCKnp3Vzv/QwczJTL+xVwP2DYUI9VrIC8ElpkmjMCHkJ4P/Ztu2SIy40UGcVklrBJ8ls6yLJrBHdedg+2mAORS0ut9hnogCzV5EGQJtAzH0LK9IbgGG27NTf/OfwTDzrz0stjWjvPG0aUDgxwpL5BKYpMuDwVnOZ6dufN8fPjfSusfnty4csUuWS7S41CCBT3lQ407Ld07UD0WbP/S/6vQotQE4cup/46Mkw6KCFglx5nkHH9u2pKrXot76uXo5mHAjFGx9jAJVINP6dIfsaVgpo/c/hxaEaSsprnuom4vEDtGM1CqVLhjb4quyppEjCKXTI5RJ//ambcVig2ns7tqb50tOqo4xM72CrcSGD+WlMcIoVVzrufQm47AGJsxB7vgtsU6D305rLAU8IO5D1l31it/zCweWET5x72gR691Qs4IeQa/ws0h/lE8EQbUNQY355UQNi+fyVgv5Jn0WqzhqJcPP9JfVPpkdiJ+zPHQvyuYg/17oTAi4kMm9CuprPOeRH6Yije42IxGXjg0H9U444LIFE1CI3O2krWK6ZBlbAt3BbX0fBcsIOERp90p0XG5/HXvbFim5gjGbZZ0IEOW6Sz/uDVp8jnQfwtSvKRySTJWQS/4G3mN6VCJE2CwgZrdQpnXrz9vwzwVnpoZhm6feKhQqB/RF4txBjOhMIOgCvQkJ9e/tNdCMsgeGv1p21af/OMBph1OXkWgwGw==
  template:
    metadata:
      name: dns-cloudflare-secret
      namespace: cert-manager
