apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-repositories.yaml
  - tsidp-egress-proxygroup.yaml
  - tsidp-egress-service.yaml
  - ts-dns.yaml
  - flux-web-rbac.yaml
  - flux-web-tls-certificate.yaml
  - tsidp-viewer-clusterrolebinding.yaml
  - k3s-upgrade.yaml
  - cluster-issuers.yaml
  - dns-cloudflare-sealed-secret.yaml
  - traefik-config.yaml
  - connector.yaml
  - imageupdateautomation.yaml
  - flux-instance
  - local-storage-class.yaml
  - ts-default-proxy-class.yaml
  - copilot-agent-rbac
  - web-public.yaml
  - monitoring-wildcard-tls.yaml
  - ts-ingress-arkham.yaml
  - arc-runners


configMapGenerator:
  - name: coredns-custom
    namespace: kube-system
    options:
      disableNameSuffixHash: true
    files:
      - tsidp-egress.server
      - ts.net.server
      - arkham.docker.local.server
