apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - tailscale
  - system-upgrade
  - networking
  - cluster-core
  - flux
  - ci
  - flux-instance
  - flux-web
  - tsidp
