deploymentStrategy:
  type: Recreate
coder:
  podSecurityContext:
    fsGroup: 1000
  tls:
    secretNames:
      - coder-tls
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "2Gi"
  service:
    type: ClusterIP
    annotations:
      external-dns.alpha.kubernetes.io/hostname: coder.${PRIVATE_DOMAIN}
  ingress:
    enable: false
