apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base/error-pages

configMapGenerator:
  - name: error-pages-helm-values
    literals: []
    options:
      disableNameSuffixHash: true
