apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: 'prometheus'
      tracesToLogsV2:
        datasourceUid: 'loki'
      nodeGraph:
        enabled: true
