---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: tailscale-operator-secret
  namespace: flux-system
spec:
  encryptedData:
    oauth-client-secret: AgBaVAgh3Y3U7b2WgTYCyKgidrQj+dZY1/FcCKLnQohPpd8ih0HOKPRR2gOCkwcWmGyxiKYLXStIYmsuwoKzaEIffpL9rJ0d3VqEkSmpXLbxrHAns76Ud6IrHlJAUVNj0EMLbQpZDKTSSG0laWmL7+MIi5oAB5WBIhUq7hmmjGQ1b25/X4Apa37Ru+0mRZLXeoZ2n6PmW737ECtVos0nOdoLIn1JNEOI7VniBV7bP//f2CRzeSF8cOz4Q/SUzq161BKLwyqUiaIE5h/wBE8eT8YbLzU3qi2lXPfhptrhivs1c10A1cMJIUKI27dcWDtZRxIXk82TyaYdcOCCZpaH2ZkV1zwXwhBHWrEKdB389XJsvNyLKS7L0etn9gL9TgVPy9WfR7Jo6N0KN9rJwMawUPoWD8xKeERHkl/pyMxH/Y62KgfzYbOP5d57LQ3ujnHQ2sLhTXVCumZuW812Vor3wZhIPbY4x4x+vORr5Ae+TATZRT3y+22eoNJt2ER+ptvQ9gf8fcxq1HcipW/zPqt4ne8eVgHMjX6jjXanlhUWMSgva5ZVwBxHagjlEHxYLfg78wGSOwYRP6GaASVwwxDG7XproBkJzROgn5pytl8wEpwzWXOmula1lViAE2us2gseqHZehN6St3b6n6yc1gMuBbonp20lj1KCRVR++TC0+byhHM4K/9oevGW+/ItNVcGMr7AdO8iCiODwQk96FuxoHu49T/LRvhBvB6avKYJ9+ggs7HKzpAbub4iX8RHsgx5FtjVFCNlHQAK3trE1kmdNu8PQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: tailscale-operator-secret
      namespace: flux-system
