apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apprise-api
  namespace: arkham
spec:
  releaseName: apprise-api
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 10m
  values:
    image:
      repository: lscr.io/linuxserver/apprise-api # {"$imagepolicy": "flux-system:apprise-api-policy:name"}
      tag: "latest" # {"$imagepolicy": "flux-system:apprise-api-policy:tag"}
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
    volumes:
      - name: config
        size: "100Mi"
        path: /config
        subPath: apprise-api/config
        existingClaim: pvc-storage
    containerPort: 8000
    probe:
      enabled: true
      path: /status
      settings:
        initialDelaySeconds: 5
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /status
      settings:
        initialDelaySeconds: 5
        timeoutSeconds: 10
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: apprise-api
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/apprise-api
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: apprise-api-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: apprise-api
  filterTags:
    pattern: '^version-v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$'
    extract: "$major.$minor.$patch"
  policy:
    semver:
      range: 1.x
