apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: arkham
spec:
  releaseName: bazarr
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 10m
  values:
    image:
      repository: lscr.io/linuxserver/bazarr # {"$imagepolicy": "flux-system:bazarr-policy:name"}
      tag: "1.5.1" # {"$imagepolicy": "flux-system:bazarr-policy:tag"}
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
    volumes:
      - name: storage
        size: "100Mi"
        path: /config
        subPath: bazarr/config
        existingClaim: pvc-storage
      - name: library
        size: "100Mi"
        path: /media/library
        existingClaim: pvc-library
      - name: backups
        size: "500Mi"
        path: /backups
        subPath: bazarr/backups
        existingClaim: pvc-backups
    containerPort: 6767
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      host: arkham.${ts_net}
      path: /bazarr
    probe:
      enabled: true
      path: /bazarr/ping
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /bazarr/ping
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 10
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bazarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/bazarr
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bazarr-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bazarr
  policy:
    semver:
      range: 1.x
