apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: arkham
spec:
  releaseName: flaresolverr
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr # {"$imagepolicy": "flux-system:flaresolverr-policy:name"}
      tag: "v3.3.21" # {"$imagepolicy": "flux-system:flaresolverr-policy:tag"}
    resources:
      requests:
        cpu: "2"
        memory: "2Gi"
      limits:
        cpu: "8"
        memory: "8Gi"
    vars:
      TZ: ${TZ:=Etc/UTC}
      BROWSER_TIMEOUT: 120000
      LANG: en_US
    containerPort: 8191
    probe:
      enabled: true
      path: /health
      settings:
        initialDelaySeconds: 10
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /health
      settings:
        initialDelaySeconds: 15
        timeoutSeconds: 10
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  image: ghcr.io/flaresolverr/flaresolverr
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: flaresolverr-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flaresolverr
  filterTags:
    pattern: '^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$'
    extract: "$major.$minor.$patch"
  policy:
    semver:
      range: 3.x
