apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: arkham
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: lscr.io/linuxserver/jellyfin # {"$imagepolicy": "flux-system:jellyfin-policy:name"}
      tag: "10.10.3" # {"$imagepolicy": "flux-system:jellyfin-policy:tag"}
    resources:
      requests:
        cpu: "1"
        memory: "512Mi"
        gpu.intel.com/i915: "1"
      limits:
        cpu: "8"
        memory: "4Gi"
        gpu.intel.com/i915: "1"
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
      VERSION: docker
    podSecurityContext:
      fsGroup: ${PGID:=1000}
    volumes:
      - name: storage
        size: "100Mi"
        path: /config
        subPath: jellyfin/config
        existingClaim: pvc-storage
      - name: library
        size: "100Mi"
        path: /media/library
        existingClaim: pvc-library
      - name: transcode
        size: "10Gi"
        path: /transcode
        hostPath:
          path: /tmp/jellyfin
          type: DirectoryOrCreate
      - name: backups
        size: "500Mi"
        path: /backups
        subPath: jellyfin
        existingClaim: pvc-backups
    containerPort: 8096
    probe:
      enabled: true
      path: /health
      settings:
        initialDelaySeconds: 10
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /health
      settings:
        initialDelaySeconds: 15
        timeoutSeconds: 10
    podSpec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    container:
      ports:
        - name: http
          containerPort: 8096
          hostPort: 8096
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/jellyfin
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jellyfin-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jellyfin
  policy:
    semver:
      range: 10.x
  digestReflectionPolicy: Always
  interval: 24h
