apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: arkham
spec:
  releaseName: lidarr
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: lscr.io/linuxserver/lidarr # {"$imagepolicy": "flux-system:lidarr-policy:name"}
      tag: "2.13.3" # {"$imagepolicy": "flux-system:lidarr-policy:tag"}
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
    podSecurityContext:
      fsGroup: ${PGID:=1000}
    volumes:
      - name: storage
        size: "100Mi"
        path: /config
        subPath: lidarr/config
        existingClaim: pvc-storage
      - name: downloads
        size: "100Mi"
        path: /downloads
        existingClaim: pvc-downloads
      - name: library
        size: "100Mi"
        path: /media/library
        existingClaim: pvc-library
      - name: backups
        size: "500Mi"
        path: /backups
        subPath: lidarr/backups
        existingClaim: pvc-backups
    containerPort: 8686
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      host: arkham.${ts_net}
      path: /lidarr
    probe:
      enabled: true
      path: /lidarr/ping
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /lidarr/ping
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 10
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lidarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/lidarr
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lidarr-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lidarr
  policy:
    semver:
      range: 2.x
  digestReflectionPolicy: Always
  interval: 24h
