apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: arkham
spec:
  releaseName: plex
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: lscr.io/linuxserver/plex # {"$imagepolicy": "flux-system:plex-policy:name"}
      tag: "1.41.8" # {"$imagepolicy": "flux-system:plex-policy:tag"}
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
        gpu.intel.com/i915: "1"
      limits:
        cpu: "8"
        memory: "8Gi"
        gpu.intel.com/i915: "1"
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
      VERSION: docker
    podSecurityContext:
      fsGroup: ${PGID:=1000}
    volumes:
      - name: storage
        size: "100Mi"
        path: /config
        subPath: plex/config
        existingClaim: pvc-storage
      - name: library
        size: "100Mi"
        path: /media/library
        existingClaim: pvc-library
      - name: transcode
        size: "10Gi"
        path: /transcode
        hostPath:
          path: /tmp/plex
          type: DirectoryOrCreate
      - name: backups
        size: "500Mi"
        path: /backups
        subPath: plex
        existingClaim: pvc-backups
    containerPort: 32400
    probe:
      enabled: true
      path: /identity
      settings:
        initialDelaySeconds: 10
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /identity
      settings:
        initialDelaySeconds: 15
        timeoutSeconds: 10
    podSpec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    container:
      ports:
        - name: http
          containerPort: 32400
          hostPort: 32400
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/plex
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: plex-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
  policy:
    semver:
      range: 1.x
  digestReflectionPolicy: Always
  interval: 24h
