---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-storage
    namespace: arkham  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: pv-arkham-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-downloads
    namespace: arkham  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
  volumeName: pv-arkham-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-watch
    namespace: arkham  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: pv-arkham-watch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-library
    namespace: arkham  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: pv-arkham-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-backups
    namespace: arkham  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-plex-logs
    namespace: arkham  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: pv-arkham-plex-logs
