apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: arkham
spec:
  releaseName: qbittorrent
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: lscr.io/linuxserver/qbittorrent # {"$imagepolicy": "flux-system:qbittorrent-policy:name"}
      tag: "5.1.1" # {"$imagepolicy": "flux-system:qbittorrent-policy:tag"}
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "4"
        memory: "4Gi"
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
      TORRENTING_PORT: 51413
    volumes:
      - name: config
        size: "100Mi"
        path: /config
        subPath: qbittorrent/config
        existingClaim: pvc-storage
      - name: downloads
        size: "100Mi"
        path: /downloads
        existingClaim: pvc-downloads
      - name: watch
        size: "100Mi"
        path: /watch
        existingClaim: pvc-watch
    containerPort: 8080
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/router.middlewares: arkham-strip-prefix@kubernetescrd
      host: arkham.${ts_net}
      path: /qbittorrent
    container:
      ports:
        - name: http
          containerPort: 8080
        - name: tcp
          protocol: TCP
          containerPort: 51413
          hostPort: 51413
        - name: udp
          protocol: UDP
          containerPort: 51413
          hostPort: 51413
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/qbittorrent
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: qbittorrent-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: qbittorrent
  policy:
    semver:
      range: 5.x
  digestReflectionPolicy: Always
  interval: 24h
