apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: arkham
spec:
  releaseName: radarr
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 10m
  values:
    image:
      repository: lscr.io/linuxserver/radarr # {"$imagepolicy": "flux-system:radarr-policy:name"}
      tag: "5.17.2" # {"$imagepolicy": "flux-system:radarr-policy:tag"}
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
    volumes:
      - name: storage
        size: "100Mi"
        path: /config
        subPath: radarr/config
        existingClaim: pvc-storage
      - name: downloads
        size: "100Mi"
        path: /downloads
        existingClaim: pvc-downloads
      - name: library
        size: "100Mi"
        path: /media/library
        existingClaim: pvc-library
      - name: backups
        size: "500Mi"
        path: /backups
        subPath: radarr/backups
        existingClaim: pvc-backups
    containerPort: 7878
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      host: arkham.${ts_net}
      path: /radarr
    probe:
      enabled: true
      path: /radarr/ping
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /radarr/ping
      settings:
        initialDelaySeconds: 30
        timeoutSeconds: 10
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: radarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/radarr
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: radarr-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radarr
  policy:
    semver:
      range: 5.x
