apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: ./charts/onechart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: jellyfin-helm-values
      optional: true
  values:
    image:
      repository: lscr.io/linuxserver/jellyfin # {"$imagepolicy": "arkham:jellyfin-policy:name"}
      tag: "10.11.11" # {"$imagepolicy": "arkham:jellyfin-policy:tag"}
    vars:
      PUID: ${PUID:=1000}
      PGID: ${PGID:=1000}
      TZ: ${TZ:=Etc/UTC}
      VERSION: docker
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_PUBLISHED_SERVER_URL:-}
    podSecurityContext:
      fsGroup: ${PGID:=1000}
    volumes:
      - name: storage
        size: "100Mi"
        path: /config
        subPath: jellyfin/config
        existingClaim: pvc-storage
      - name: library
        size: "100Mi"
        path: /media/library
        existingClaim: pvc-library
      - name: transcode
        size: "10Gi"
        path: /transcode
      - name: backups
        size: "500Mi"
        path: /backups
        subPath: jellyfin
        existingClaim: pvc-backups
    containerPort: 8096
    ingress:
      path: /
    probe:
      enabled: true
      path: /health
      settings:
        initialDelaySeconds: 10
        timeoutSeconds: 5
    livenessProbe:
      enabled: true
      path: /health
      settings:
        initialDelaySeconds: 15
        timeoutSeconds: 10
    container:
      ports:
        - name: http
          containerPort: 8096
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: jellyfin
spec:
  image: lscr.io/linuxserver/jellyfin
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: jellyfin-policy
spec:
  imageRepositoryRef:
    name: jellyfin
  policy:
    semver:
      range: 10.x
  digestReflectionPolicy: Always
  interval: 24h
