---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set
  namespace: arc-runners
spec:
  interval: 24h
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  ref:
    semver: "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyrion-gha-rs-sa
  namespace: arc-runners
