apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: error-pages
  namespace: default
spec:
  releaseName: error-pages
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: ghcr.io/tarampampam/error-pages # {"$imagepolicy": "flux-system:error-pages-policy:name"}
      tag: "3.3.3" # {"$imagepolicy": "flux-system:error-pages-policy:tag"}
    vars:
      TEMPLATES_ROTATION_MODE: "random-on-each-request"
    containerPort: 8080
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: error-pages
  namespace: flux-system
spec:
  image: ghcr.io/tarampampam/error-pages
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: error-pages-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: error-pages
  policy:
    semver:
      range: 3.x
  digestReflectionPolicy: Always
  interval: 24h
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-error-pages@kubernetescrd
spec:
  defaultBackend:
    service:
      name: error-pages
      port:
        name: http
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-pages
  namespace: default
spec:
  errors:
    status:
      - "400-599"
    query: /{status}.html
    service:
      name: error-pages
      port: 8080
