---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elasticsearch-mcp-credentials
  namespace: monitoring
spec:
  encryptedData:
    ES_API_KEY: AgA2c7jw0+R6+JXu80HYd5kkXYMRqARt9aX1KKwnAKC7dFiiGl0Nl/SDAETSuQuH3QVqrrx4TCA4LZg53L/L1e+CeNjCfscLFDuOjCDjGsxnFYU7hLX4dAnUFXoRie+tyRKpQ9vM52rhNA/4p2JygLXsIO+U49ueJiHgtf9DkPz1xWfImjb8HNsElSUepYZpWCrgzSosPHXkTjSFRauDg8dR/gcff0YI3IKgpEFK4FXaug/pLIdOqK8ZfUIV0o7IRFAsruYySAwSZV3Orh2EaFhyWxdKXwwyavbD2Dw1mQ6W8Dw3RG8TVt33aidHDmx0wvyNfFVBUORIidul8r+uV8I/6W13aslI4JuaIDfXPv2UdADoOSrbJB8YqLi6/40N2ARI/X0Ig732DDZVUnEkQjQrlkD9wsgLSAd0lcLDG9eE5/twFKJRwCR6Q6t9zg0nzQ9OFtXb9/WHgL/JkQMyxPJA481GKzX7AT22a6AwrycGjGkXfBNJnHbZWTd2/89YwkgAkyPFk1wZkGY7vLEJVPBQO2LEGvRw3mfUC28Acy0QydrlULWWr7DRMXh2I8hg+c7s8XJKI8XVqCHWPdagiJdBxf9zvPAWhqx+VsC1iexECJlF0n7FUFX7AhoIJQLZ7KdPw7IzVcRz2HFAQI8pgi17nstnVwgqDvt1nvZXcPY7yke2cu+yZklrf/WbKxcAr+cKI3TnuGt4nyVeHRRcRdydalh2AA==
  template:
    metadata:
      name: elasticsearch-mcp-credentials
      namespace: monitoring
