---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-mcp
  namespace: monitoring
  labels:
    app: elasticsearch-mcp
spec:
  selector:
    app: elasticsearch-mcp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-mcp
  namespace: monitoring
  labels:
    app: elasticsearch-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-mcp
  template:
    metadata:
      labels:
        app: elasticsearch-mcp
    spec:
      containers:
      - name: elasticsearch-mcp
        image: docker.elastic.co/mcp/elasticsearch:latest  # {"$imagepolicy": "flux-system:elasticsearch-mcp-policy:tag"}
        args:
          - "http"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: ES_URL
          value: "https://elasticsearch-es-http.monitoring.svc.cluster.local:9200"
        envFrom:
        - secretRef:
            name: elasticsearch-mcp-credentials
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-mcp
  namespace: monitoring
  annotations:
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
spec:
  ingressClassName: tailscale
  rules:
  - host: elasticsearch-mcp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-mcp
            port:
              number: 8080
  tls:
  - hosts:
    - elasticsearch-mcp
---
# ImageRepository for automated image updates
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: elasticsearch-mcp
  namespace: flux-system
spec:
  image: docker.elastic.co/mcp/elasticsearch
  interval: 24h
---
# ImagePolicy for automated image updates
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: elasticsearch-mcp-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: elasticsearch-mcp
  policy:
    semver:
      range: "*"
