---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: langflow
  namespace: ai
spec:
  type: default
  interval: 24h
  url: https://langflow-ai.github.io/langflow-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langflow
  namespace: ai
spec:
  releaseName: langflow
  chart:
    spec:
      chart: langflow-ide
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: langflow
        namespace: ai
  interval: 12h
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    # Override service name to avoid env var collision on OpenShift
    nameOverride: "langflow-service"
    fullnameOverride: "langflow-service"

    langflow:
      # Backend configuration
      backend:
        replicaCount: 1
        image:
          repository: langflowai/langflow # {"$imagepolicy": "flux-system:langflow-policy:name"}
          tag: "1.1.1" # {"$imagepolicy": "flux-system:langflow-policy:tag"}
          imagePullPolicy: IfNotPresent

        # Resource allocation
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi

        # Environment variables
        env:
          - name: LANGFLOW_PORT
            value: "7860"
          - name: LANGFLOW_AUTO_LOGIN
            value: "false"
          - name: LANGFLOW_CACHE_TYPE
            value: "memory"
          - name: LANGFLOW_LOG_LEVEL
            value: "info"
          - name: LANGFLOW_DATABASE_URL
            value: "postgresql://langflow:langflow@langflow-postgresql:5432/langflow"
          - name: LANGFLOW_CONFIG_DIR
            value: "/app/data"

        # Use persistent volumes instead of emptyDir
        volumes:
          - name: flows
            persistentVolumeClaim:
              claimName: langflow-flows
          - name: tmp
            emptyDir: {}
          - name: data
            persistentVolumeClaim:
              claimName: langflow-data
          - name: db
            emptyDir: {}

        volumeMounts:
          - name: flows
            mountPath: /app/flows
            readOnly: false
          - name: tmp
            mountPath: /tmp
            readOnly: false
          - name: data
            mountPath: /app/data
            readOnly: false
          - name: db
            mountPath: /app/db
            readOnly: false

        # Disable SQLite in favor of PostgreSQL
        sqlite:
          enabled: false

      # Frontend configuration
      frontend:
        enabled: true
        replicaCount: 1
        image:
          repository: langflowai/langflow-frontend
          tag: latest
          imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi

    # Ingress configuration for Tailscale
    ingress:
      enabled: true
      className: tailscale
      hosts:
        - host: langflow.${ts_net}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - langflow

    # Use external PostgreSQL (deployed separately)
    postgresql:
      enabled: false
---
# Persistent Volume Claim for flows
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langflow-flows
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
# Persistent Volume Claim for data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langflow-data
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
# PostgreSQL HelmRelease using Bitnami chart
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langflow-postgresql
  namespace: ai
spec:
  releaseName: langflow-postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "16.x.x"
  interval: 12h
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    auth:
      username: langflow
      password: langflow
      database: langflow
      existingSecret: ""
    primary:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path
    metrics:
      enabled: false
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: langflow
  namespace: flux-system
spec:
  image: langflowai/langflow
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: langflow-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: langflow
  policy:
    semver:
      range: ">=1.0.0 <2.0.0"  # Match 1.x versions
  digestReflectionPolicy: Always
  interval: 24h
