---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: librechat
  namespace: ai
spec:
  interval: 24h
  url: https://github.com/danny-avila/LibreChat.git
  ref:
    branch: main
  ignore: |
    /*
    !/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librechat
  namespace: ai
spec:
  releaseName: librechat
  chart:
    spec:
      chart: helm/librechat
      sourceRef:
        kind: GitRepository
        name: librechat
  interval: 12h
  values:
    global:
      librechat:
        existingSecretApiKey: AZURE_API_KEY
    
    librechat:
      configEnv:
        NO_INDEX: "true"
        ENDPOINTS: agents,google,azureAssistants,azureOpenAI,custom
        ALLOW_EMAIL_LOGIN: "false"
        ALLOW_REGISTRATION: "false"
        ALLOW_SOCIAL_LOGIN: "true"
        ALLOW_SOCIAL_REGISTRATION: "true"
        ALLOW_PASSWORD_RESET: "false"
        ALLOW_ACCOUNT_DELETION: "true"
        ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"
        DOMAIN_CLIENT: https://chat.${ts_net}
        DOMAIN_SERVER: https://chat.${ts_net}
        GOOGLE_CALLBACK_URL: /oauth/google/callback
        GOOGLE_MODELS: gemini-1.5-flash-latest,gemini-1.0-pro,gemini-1.0-pro-001,gemini-1.0-pro-latest,gemini-1.0-pro-vision-latest,gemini-1.5-pro-latest,gemini-pro,gemini-pro-vision
        GITHUB_CALLBACK_URL: /oauth/github/callback
      existingConfigYaml: librechat-config
    ingress:
      enabled: true
      className: tailscale
      hosts:
      - paths:
          - path: /
            pathType: Prefix
      tls:
        - hosts:
            - chat
