---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: librechat
  namespace: ai
spec:
  type: oci
  url: oci://ghcr.io/danny-avila/librechat-chart
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librechat
  namespace: ai
spec:
  releaseName: librechat
  chart:
    spec:
      chart: librechat
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: librechat
        namespace: ai
      interval: 12h
  interval: 30m
  values:
    global:
      librechat:
        existingSecretApiKey: AZURE_API_KEY

    librechat:
      configEnv:
        NO_INDEX: "true"
        ENDPOINTS: agents,google,azureAssistants,azureOpenAI,custom
        ALLOW_EMAIL_LOGIN: "false"
        ALLOW_REGISTRATION: "false"
        ALLOW_SOCIAL_LOGIN: "true"
        ALLOW_SOCIAL_REGISTRATION: "true"
        ALLOW_PASSWORD_RESET: "false"
        ALLOW_ACCOUNT_DELETION: "true"
        ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"
        DOMAIN_CLIENT: https://chat.${ts_net}
        DOMAIN_SERVER: https://chat.${ts_net}
        GOOGLE_CALLBACK_URL: /oauth/google/callback
        GOOGLE_MODELS: gemini-1.5-flash-latest,gemini-1.0-pro,gemini-1.0-pro-001,gemini-1.0-pro-latest,gemini-1.0-pro-vision-latest,gemini-1.5-pro-latest,gemini-pro,gemini-pro-vision
        GITHUB_CALLBACK_URL: /oauth/github/callback
      existingConfigYaml: librechat-config
    ingress:
      enabled: true
      className: tailscale
      hosts:
        - paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - chat

    # Persistence configuration aligned with upstream chart defaults
    # Pin storageClass to the K3s local-path provisioner to avoid unbound PVCs
    meilisearch:
      persistence:
        enabled: true
        storageClass: local-path

    mongodb:
      enabled: true
      auth:
        enabled: false
      persistence:
        enabled: true
        size: 8Gi
        storageClass: local-path
      image:
        tag: latest
    # Store uploaded images on persistent volume; use local-path by default
    imageVolume:
      enabled: true
      size: 10G
      accessModes: ReadWriteOnce
      storageClassName: local-path
