---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otwld
  namespace: ai
spec:
  type: default
  interval: 24h
  url: https://helm.otwld.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ai
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: otwld
  interval: 12h
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    ollama:
      models:
        pull:
          - phi3
          - phi3:14b
          - gpt-oss
          - deepseek-v3.1
          - llama4
          - mistral
        run:
          - phi3

    ingress:
      enabled: true
      className: tailscale
      hosts:
        - paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - ollama

    persistentVolume:
      enabled: true
    extraEnv:
      - name: OLLAMA_INTEL_GPU
        value: "1"
    resources:
      requests:
        gpu.intel.com/i915: "1"
      limits:
        gpu.intel.com/i915: "1"
