---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: ai
spec:
  type: default
  interval: 24h
  url: https://helm.openwebui.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui
  namespace: ai
spec:
  releaseName: openwebui
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
  interval: 12h
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - http://ollama.ai.svc:11434
    ingress:
      enabled: true
      class: tailscale
      host: openwebui
      tls: true
    openaiBaseApiUrl: https://alecsg77-1293-resource.openai.azure.com/v1
    extraEnv:
      OPENID_PROVIDER_URL: https://accounts.google.com/.well-known/openid-configuration
      WEBHOOK_URL: https://openwebui.${ts_net}/webhook
      ENABLE_PERSISTENT_CONFIG: "False"
    extraEnvFrom:
      - secretRef:
          name: openwebui-credentials-env
    sso:
      enabled: true
