---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: ai
spec:
  type: default
  interval: 24h
  url: https://helm.openwebui.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui
  namespace: ai
spec:
  releaseName: openwebui
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
  interval: 12h
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - http://ollama.ai.svc:11434
    ingress:
      enabled: true
      class: tailscale
      host: chat.${ts_net}
      tls: true
    tika:
      enabled: true
    sso:
      enabled: true
      enableSignup: true
      mergeAccountsByEmail: true
      github:
        enabled: true
        clientId: Iv23li9lZj5gR8CHTERs
        clientExistingSecret: openwebui-credentials-env
        clientExistingSecretKey: GITHUB_CLIENT_SECRET
      trustedHeader:
        enabled: true
        emailHeader: Tailscale-User-Login
        nameHeader: Tailscale-User-Name