apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://github.com/fission/fission/crds/v1?ref=v1.21.0
  - repository.yaml
  - release.yaml
  - ingress.yaml
  - roles.yaml