---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fission
spec:
  releaseName: fission
  chart:
    spec:
      chart: fission-all
      sourceRef:
        name: fission-charts
        kind: HelmRepository
  interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: fission-helm-values
      valuesKey: fission-values.yaml
      optional: true
  values:
    routerServiceType: ClusterIP
    serviceMonitor:
      enabled: true
    grafana:
      dashboards:
        enable: true
