apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- registry-namespace.yaml
- registry-deployment.yaml
- registry-persistentvolumeclaim.yaml
- registry-service.yaml
- registry-ingress.yaml

patches:
  - path: registry-deployment.patch.yaml
