apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - registry.yaml
  - policy.yaml
  - automation.yaml

configMapGenerator:
  - name: registry-values
    files:
      - values.yaml=registry-values.yaml
configurations:
  - kustomizeconfig.yaml