apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: registry
  name: registry
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
