apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry
  namespace: registry
spec:
  releaseName: registry
  chart:
    spec:
      chart: onechart
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
  interval: 12h
  values:
    image:
      repository: registry # {"$imagepolicy": "flux-system:registry-policy:name"}
      tag: "2.8.3" # {"$imagepolicy": "flux-system:registry-policy:tag"}
    volumes:
      - name: registry
        size: "100Mi"
        path: /var/lib/registry
    containerPort: 5000
