apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry
spec:
  releaseName: registry
  chart:
    spec:
      chart: ./charts/onechart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: registry-helm-values
      optional: true
    - kind: ConfigMap
      name: registry-image-auto
      valuesKey: values.yaml
  values:
    volumes:
      - name: registry
        size: "100Mi"
        path: /var/lib/registry
    containerPort: 5000
