apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: romm

resources:
  - namespace.yaml
  - ../../base/romm
  - romm-db-secret-values.yaml

configMapGenerator:
  - name: romm-helm-values
    files:
      - values.yaml=romm-values.yaml
    options:
      disableNameSuffixHash: true
