---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set
  namespace: arc-runners
spec:
  interval: 24h
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  ref:
    semver: "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyrion-gha-rs-sa
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyrion-gha-rs-sa-fission-user
roleRef:
  kind: ClusterRole
  name: fission-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kyrion-gha-rs-sa
  namespace: arc-runners
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-set
  namespace: arc-runners
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-runners
  values:
    githubConfigUrl: https://github.com/alecsg77/elysium
    runnerScaleSetName: "kyrion"
    githubConfigSecret: pre-defined-secret
    containerMode:
      type: "dind"
    template:
      spec:
        serviceAccountName: kyrion-gha-rs-sa