---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: arkham
spec:
  values:
    vars:
      # Configure conditional forwarding for Kubernetes cluster domains to CoreDNS
      # Service network (10.43.0.0/24) forwards svc.cluster.local to CoreDNS
      # Pod network (10.42.0.0/24) forwards pod.cluster.local to CoreDNS
      FTLCONF_dns_revServers:
        - "true,10.43.0.0/24,10.43.0.10#53,svc.cluster.local"
        - "true,10.42.0.0/24,10.43.0.10#53,pod.cluster.local"
