---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: arkham
spec:
  values:
    vars:
      # Forward cluster.local queries to CoreDNS
      FTLCONF_dns_upstreams: '10.43.0.10#53@cluster.local'
