---
apiVersion: v1
kind: Service
metadata:
  name: coder-prom
  namespace: coder
  labels:
    app.kubernetes.io/name: coder
spec:
  clusterIP: None
  ports:
    - name: prometheus-http
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    app.kubernetes.io/instance: coder-coder
    app.kubernetes.io/name: coder
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coder-service-monitor
  namespace: coder
spec:
  endpoints:
    - port: prometheus-http
      interval: 10s
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: coder
