---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: copilot-runner-set
  namespace: arc-runners
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-runners
  values:
    githubConfigUrl: https://github.com/alecsg77/elysium
    githubConfigSecret: pre-defined-secret
    runnerScaleSetName: copilot-runner-set
    template:
      spec:
        serviceAccountName: copilot-agent-readonly
