---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-gha-rs-sa
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fission-gha-rs-sa-fission-user
roleRef:
  kind: ClusterRole
  name: fission-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fission-gha-rs-sa
  namespace: arc-runners
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fission-runner-set
  namespace: arc-runners
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-runners
  values:
    githubConfigUrl: https://github.com/alecsg77/elysium
    githubConfigSecret: pre-defined-secret
    containerMode:
      type: "dind"
    template:
      spec:
        serviceAccountName: fission-gha-rs-sa