---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_LICENSE_ACTIVATION_KEY: AgBoBh0McJVq4x4PJPDs3cS6GfevcSxQ67/kPYBhDEqSfda42RH/sl8hnctn7aDERa73GEDM6PlOhhVaUpvEQcXf8soVMytE5wmiH45e1BaZnCfd0RuxJbel4boaTR2ED8JSsJ/5oH4LtLOp7fb1eDR6kFiks2U2SF6YlAUio1583/fpGsOUkQUCNr0EFkb7YZ7pag5WMHX8LS70tGMLrrFCCYoZB/jAwKjt1hTGa0emVxDZDGB3hAJ+KtW5Pw4upRA8b/PrbHfq7P6B2y4sTgJRj2CWTcf8wM9KJCBVAXOOVFrQhc1t2j+5gnFQ37zgpPbx0cnDr3fjbBkbxnnJNKYrViOQ7BRCwbFlAkpi54/FlHARUDinWQW5dP3eJCoW1/huj+KAc0pb2kID9z4WMFrQ/OVfyrMBxU26nNc9sBLa+g9W5PfDUFBQNtwRVhkt1NIPrYhTvazQU3Vwhe2+NRWdHQvy9+hizasrFukhVOp/iqXGp0Qei2KsfxnB0ut40N7BHZyhkcJZr6k8LUwFDxH1gAl3Z4t8sXvX+GgEOOD8OuoCIJpgiptWl/gxQ6r2qwjmob9YoBQRR6ugqTdfvzxSb/QpUqNmS4n2NGMoNKKieS98YShwYVXxgL7TCUxPID5bSN0i745/xXHremouBH39HdMH5JEdEMGc0fmOZuuuCW3Zryp/Tjl+TATpWCcY8VCJYNLJv64jJYeoG+UInCgbebvVa/Z/sSBnw8/WN3OR0OqFnvM=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret
      namespace: n8n
    type: Opaque
