apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: podinfo.${DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls:
        - secretName: tls-podinfo-ingress-dns
          hosts:
            - podinfo.${DOMAIN}
