apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: raiplaysoundrss-runner-set
  namespace: arc-runners
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-runners
  values:
    githubConfigUrl: https://github.com/alecsg77/raiplaysoundrss
    runnerScaleSetName: "raiplaysoundrss"
    githubConfigSecret: pre-defined-secret
    containerMode:
      type: "dind"
