---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: romm-db-secret-values
  namespace: romm
spec:
  encryptedData:
    values.yaml: AgAhE417fdHH3CCDuBUwZRRoHSq2mzNPOSV9XdwFZKP/3stpKNykNgGNGu0x17gV+mI9pbTCSGFDLN6q4G8Jb9fMPfoxz6wznyhP6bQulpuZ0uV4b2MBgUQCqs2ADKaQxFN7ABg1CasDoZjCw+tFVfEai9pv4gmuDlF/A7WMe11rPwlwhuqCrDVbD081BvIowokO2Nb5Y0hshnEUeG7RmGVTM1XxXmSn/TtAoQp7oq69Uj0dNfE3hwzKvJ50+iCPrivE3m9VFxzbZ+T+P4wXq75FqfZcgveG6tlbsVYFQChuQG8+XLjSYF8ZfTYE4wisKEUoZA2um/16Wq+qNjigtJPrCSo9VzocgNf7NGgiUhMOqRJmhpQu6dfEa79tVCSOTs0ppzCcNoVmhM6505AcPkvS4+Jeh4cZ8UcY6fiqx4enJkw5c9vCgLga9BUM9ENMuBtcfAeTQo3jcBykdYe97umiPLTxhSNyiVTm6ng2//O9K/GZVx+klBhNq6d0BozxsDFMCkB2Z9DaRcFCxiJ5g+XiBasi/L2yNU6AUrKba3O0iN0kicb/qNZX9rU5CBmvIWEpq/z6NIYD3XmlhE/NaN6sDXrOs8AigSKNf9LUITC3kvvEdP0CZekpv7uXwhA5fQ9a/zCRJniJioT8NPxqyN9DOpVLkO+k3WJjn7TcGA7zT4FbP6j7T9Z39325k7I8LCXmPViV1B8Ow8e0GRXpDR1P8tTEu+X0Kf3oVAvdGoYtcQ==
  template:
    metadata:
      creationTimestamp: null
      name: romm-db-secret-values
      namespace: romm
