---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-public
  namespace: default
spec:
  secretName: tls-web-public-dns
  dnsNames:
    - ${DOMAIN}
    - "*.${DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
