---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: default
spec:
  type: ExternalName
  externalName: overseerr.arkham.docker.local
---
apiVersion: v1
kind: Service
metadata:
  name: raiplaysoundrss
  namespace: default
spec:
  type: ExternalName
  externalName: rss.arkham.docker.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-public
  namespace: default
spec:
  secretName: tls-web-public-dns
  dnsNames:
    - ${DOMAIN}
    - "*.${DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-public
  namespace: default

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.${DOMAIN}`)
      kind: Rule
      services:
        - name: overseerr
          port: 5055
  tls:
    secretName: tls-web-public-dns
